In [1]:
import os
import pandas as pd
from pathlib import Path
import sys

BASE_DIR = Path.cwd().parent
PROCESSED_DIR = BASE_DIR / "data" / "processed" 
PROCESSED_FEATURE_DIR = PROCESSED_DIR / "features"

COMPANIES_DIR = BASE_DIR / "data" / "raw" / "companies"

sys.path.append(str(BASE_DIR))

returns_df = pd.read_parquet(os.path.join(COMPANIES_DIR, "returns.parquet"))

feature_matrix_pipeline_dict = {
    "feature_matrix_stock": os.path.join(PROCESSED_FEATURE_DIR, "feature_matrix_stock.parquet"), 
    "feature_matrix_market": os.path.join(PROCESSED_FEATURE_DIR, "feature_matrix_market.parquet"), 
    "feature_matrix_macro_market": os.path.join(PROCESSED_FEATURE_DIR, "feature_matrix_macro_market.parquet")
}

In [2]:
from scripts.models.lr.lr_model import LinearRegressionModel

from scripts.models.dt.tune_dt import DTTuner
from scripts.models.dt.dt_model import DTRegressionModel

from scripts.models.lightgbm.tune_lightgbm import LightGBMTuner
from scripts.models.lightgbm.lightgbm_model import LightGBMRegressionModel

from scripts.models.xgboost.tune_xgboost import XGBoostTuner
from scripts.models.xgboost.xgboost_model import XGBoostRegressionModel
from scripts.models.walk_forward import WalkForwardValidator

from scripts.models.gru.tune_gru import GRUTuner
from scripts.models.gru.gru_model import GRURegressionModel
from scripts.models.walk_forward_gru import WalkForwardGRUValidator

WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
I0000 00:00:1784217439.435247     600 port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
I0000 00:00:1784217439.992989     600 cpu_feature_guard.cc:227] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
I0000 00:00:1784217442.270011     600 port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.

In [3]:
feature_matrix_stock = pd.read_parquet(feature_matrix_pipeline_dict["feature_matrix_stock"])
feature_matrix_market = pd.read_parquet(feature_matrix_pipeline_dict["feature_matrix_market"])
feature_matrix_macro_market = pd.read_parquet(feature_matrix_pipeline_dict["feature_matrix_macro_market"])

In [10]:
feature_matrix_unscaled = feature_matrix_stock.columns

market_scaled_columns = feature_matrix_market.columns.difference(feature_matrix_unscaled).tolist()
macro_market_scaled_columns = feature_matrix_macro_market.columns.difference(feature_matrix_unscaled).tolist()

In [19]:
feature_matrix_unscaled

Index(['Date', 'Ticker', 'autocorr_21', 'autocorr_63', 'market_beta_63',
       'industry_beta_63', 'market_resid_vol_126', 'industry_resid_vol_126',
       'mean_volatility_10', 'mean_volatility_21', 'mean_volatility_63',
       'amihud_21', 'momentum_252_21', 'momentum_liquidity_21', 'reversal_5',
       'rsr_21', 'trend_21', 'trend_63', 'trend_126', 'r2_21', 'r2_63',
       'r2_126', 'future_return_5d'],
      dtype='object')

In [4]:
feature_matrix_market.columns

Index(['Date', 'Ticker', 'autocorr_21', 'autocorr_63', 'market_beta_63',
       'industry_beta_63', 'market_resid_vol_126', 'industry_resid_vol_126',
       'mean_volatility_10', 'mean_volatility_21', 'mean_volatility_63',
       'amihud_21', 'momentum_252_21_x', 'momentum_liquidity_21', 'reversal_5',
       'rsr_21', 'trend_21', 'trend_63', 'trend_126', 'r2_21', 'r2_63',
       'r2_126', 'future_return_5d', 'market_return_1d', 'market_return_5d',
       'market_return_21d', 'momentum_63_21', 'momentum_252_21_y',
       'market_volatility_21d', 'market_volatility_63d', 'raw_garch_vol',
       'market_drawdown_21d', 'market_drawdown_63d', 'market_drawdown_252d'],
      dtype='object')

In [4]:
pickle_model_stock_paths = { 
    "gru_model_stock": os.path.join(BASE_DIR, "results/gru_model/gru_model_stock.pkl"),
    "dt_model_stock": os.path.join(BASE_DIR, "results/dt_model/dt_model_stock.pkl"),
    "lightgbm_model_stock": os.path.join(BASE_DIR, "results/lightgbm_model/lightgbm_model_stock.pkl"), 
    "xgboost_model_stock": os.path.join(BASE_DIR, "results/xgboost_model/xgboost_model_stock.pkl")
}

pickle_model_market_paths = { 
    "gru_model_market": os.path.join(BASE_DIR, "results/gru_model/gru_model_market.pkl"),
    "dt_model_market": os.path.join(BASE_DIR, "results/dt_model/dt_model_market.pkl"),
    "lightgbm_model_market": os.path.join(BASE_DIR, "results/lightgbm_model/lightgbm_model_market.pkl"), 
    "xgboost_model_market": os.path.join(BASE_DIR, "results/xgboost_model/xgboost_model_market.pkl")
}

pickle_model_macro_market_paths = {
    "gru_model_macro_market": os.path.join(BASE_DIR, "results/gru_model/gru_model_macro_market.pkl"),
    "dt_model_macro_market": os.path.join(BASE_DIR, "results/dt_model/dt_model_macro_market.pkl"),
    "lightgbm_model_macro_market": os.path.join(BASE_DIR, "results/lightgbm_model/lightgbm_model_macro_market.pkl"), 
    "xgboost_model_macro_market": os.path.join(BASE_DIR, "results/xgboost_model/xgboost_model_macro_market.pkl")
}

In [5]:
import tensorflow as tf
print(tf.config.list_physical_devices("GPU"))

[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [5]:
import json
import pickle

### Company Wide Feature Matrix

In [17]:
lr = LinearRegressionModel()

wf = WalkForwardValidator(
    feature_matrix=feature_matrix_macro_market,
    model=lr,
    validation_start="2025-07-01",
    validation_end="2026-12-31",
    rebalance_date=1,
    min_train_size=25000,
)

X_test, test_preds = wf.run_data()

daily_ic = test_preds.groupby("Date").apply(
    lambda x: x["prediction"].corr(
        x["future_return_5d"],
        method="spearman",
    ),
    include_groups = False
)

mean_ic = daily_ic.dropna().mean()

In [18]:
mean_ic

np.float64(0.047419945350007)

In [6]:
DTTuner(20, 42, feature_matrix_stock, "stock").run_data()

1/20: IC = 0.02101
2/20: IC = 0.02424
3/20: IC = 0.01723
4/20: IC = 0.01296
5/20: IC = 0.00955
6/20: IC = 0.00093
7/20: IC = 0.02379
8/20: IC = 0.02314
9/20: IC = 0.02138
10/20: IC = 0.01986
11/20: IC = 0.02444
12/20: IC = 0.03874
13/20: IC = 0.00652
14/20: IC = 0.04135
15/20: IC = 0.01360
16/20: IC = 0.01850
17/20: IC = 0.01737
18/20: IC = 0.02336
19/20: IC = 0.01028
20/20: IC = 0.02769

In [ ]:
results_dt_stock_df = pd.read_csv(os.path.join(BASE_DIR, "results/dt_model/random_search_stock.csv"))
results_dt_stock_df.head()

with open(os.path.join(BASE_DIR, "results/dt_model/best_params_stock.json"), "r") as f:
    best_dt_stock_params = json.load(f)
    
int_dt_params = [
    "max_depth",
    "min_samples_split",
    "min_samples_leaf"
]

for p in int_dt_params:
    best_dt_stock_params[p] = int(best_dt_stock_params[p])
    
dt_stock_model = LightGBMRegressionModel(params=best_dt_stock_params)

with open(pickle_model_stock_paths["dt_model_stock"], "wb") as file: 
    pickle.dump(dt_stock_model, file)
    
with open(pickle_model_stock_paths["dt_model_stock"], "rb") as file: 
    dt_stock_v2 = pickle.load(file)
    
wf = WalkForwardValidator(
    feature_matrix=feature_matrix_stock,
    model=dt_stock_v2,
    validation_start="2025-07-01",
    validation_end="2026-12-31",
    rebalance_date=1,
    min_train_size=25000,
)

X_test, test_preds = wf.run_data()

daily_ic = test_preds.groupby("Date").apply(
    lambda x: x["prediction"].corr(
        x["future_return_5d"],
        method="spearman",
    ),
    include_groups = False
)

mean_ic = daily_ic.dropna().mean()

In [7]:
results_dt_stock_df = pd.read_csv(os.path.join(BASE_DIR, "results/dt_model/random_search_stock.csv"))
results_dt_stock_df.head()

   max_depth  min_samples_split  min_samples_leaf  max_features   mean_ic
0          5                100                10           0.5  0.041347
1          5                 20                20           0.5  0.038738
2          4                 20                20           0.5  0.027695
3          3                 50                10           NaN  0.024445
4          3                 20                10           0.8  0.024241

In [8]:
with open(os.path.join(BASE_DIR, "results/dt_model/best_params_stock.json"), "r") as f:
    best_dt_stock_params = json.load(f)

In [10]:
int_dt_params = [
    "max_depth",
    "min_samples_split",
    "min_samples_leaf"
]

for p in int_dt_params:
    best_dt_stock_params[p] = int(best_dt_stock_params[p])

In [11]:
dt_stock_model = LightGBMRegressionModel(params=best_dt_stock_params)

with open(pickle_model_stock_paths["dt_model_stock"], "wb") as file: 
    pickle.dump(dt_stock_model, file)

In [12]:
with open(pickle_model_stock_paths["dt_model_stock"], "rb") as file: 
    dt_stock_v2 = pickle.load(file)

In [13]:
wf = WalkForwardValidator(
    feature_matrix=feature_matrix_stock,
    model=dt_stock_v2,
    validation_start="2025-07-01",
    validation_end="2026-12-31",
    rebalance_date=1,
    min_train_size=25000,
)

X_test, test_preds = wf.run_data()

daily_ic = test_preds.groupby("Date").apply(
    lambda x: x["prediction"].corr(
        x["future_return_5d"],
        method="spearman",
    ),
    include_groups = False
)

mean_ic = daily_ic.dropna().mean()

In [14]:
mean_ic

np.float64(0.027982726050651403)

#### LightGBM

In [6]:
LightGBMTuner(20, 42, feature_matrix_stock, "stock").run_data()

1/20: IC = 0.02809
2/20: IC = 0.03027
3/20: IC = 0.03006
4/20: IC = 0.01855
5/20: IC = 0.02759
6/20: IC = 0.03432
7/20: IC = 0.02748
8/20: IC = 0.03119
9/20: IC = 0.01819
10/20: IC = 0.01745
11/20: IC = 0.03407
12/20: IC = 0.01409
13/20: IC = 0.01656
14/20: IC = 0.00390
15/20: IC = 0.02210
16/20: IC = 0.03091
17/20: IC = 0.02585
18/20: IC = 0.01486
19/20: IC = 0.02583
20/20: IC = 0.02404

In [7]:
results_lightgbm_stock_df = pd.read_csv(os.path.join(BASE_DIR, "results/lightgbm_model/random_search_stock.csv"))
results_lightgbm_stock_df.head()

,learning_rate,num_leaves,max_depth,n_estimators,min_child_samples,mean_ic
0,0.08,63,9,200,20,0.034324
1,0.02,63,5,200,10,0.034073
2,0.04,63,9,100,100,0.031193
3,0.01,31,5,300,100,0.030914
4,0.02,127,5,100,100,0.030269

In [ ]:
with open(os.path.join(BASE_DIR, "results/lightgbm_model/best_params_stock.json"), "r") as f:
    best_lightgbm_stock_params = json.load(f)

In [38]:
int_lightgbm_params = [
    "num_leaves",
    "max_depth",
    "n_estimators",
    "min_child_samples",
]

for p in int_lightgbm_params:
    best_lightgbm_stock_params[p] = int(best_lightgbm_stock_params[p])

In [24]:
lightgbm_stock_model = LightGBMRegressionModel(params=best_lightgbm_stock_params)

with open(pickle_model_stock_paths["lightgbm_model_stock"], "wb") as file: 
    pickle.dump(lightgbm_stock_model, file)

In [25]:
with open(pickle_model_stock_paths["lightgbm_model_stock"], "rb") as file: 
    lightgbm_stock_v2 = pickle.load(file)

In [28]:
wf = WalkForwardValidator(
    feature_matrix=feature_matrix_stock,
    model=lightgbm_stock_v2,
    validation_start="2025-07-01",
    validation_end="2026-12-31",
    rebalance_date=1,
    min_train_size=25000,
)

X_test, test_preds = wf.run_data()

daily_ic = test_preds.groupby("Date").apply(
    lambda x: x["prediction"].corr(
        x["future_return_5d"],
        method="spearman",
    ),
    include_groups = False
)

mean_ic = daily_ic.dropna().mean()

In [32]:
mean_ic.astype("float32")

np.float32(0.020762276)

#### XGBoost

In [33]:
XGBoostTuner(20, 42, feature_matrix_stock, "stock").run_data()

1/20: IC = 0.01632
2/20: IC = 0.03080
3/20: IC = 0.02464
4/20: IC = 0.01850
5/20: IC = 0.02925
6/20: IC = 0.02273
7/20: IC = 0.00860
8/20: IC = 0.01570
9/20: IC = 0.03015
10/20: IC = 0.03154
11/20: IC = 0.02845
12/20: IC = 0.00879
13/20: IC = 0.02795
14/20: IC = 0.02717
15/20: IC = 0.01741
16/20: IC = 0.01432
17/20: IC = 0.02059
18/20: IC = 0.02791
19/20: IC = 0.01429
20/20: IC = 0.02044

In [35]:
results_xgboost_stock_df = pd.read_csv(os.path.join(BASE_DIR, "results/xgboost_model/random_searchstock.csv"))
results_xgboost_stock_df.head()

   learning_rate  max_depth  n_estimators  min_child_weight   mean_ic
0           0.01          3           500                10  0.031537
1           0.02          4           200                10  0.030796
2           0.04          4           200                50  0.030146
3           0.02          7           100                20  0.029247
4           0.04          5           300                10  0.028449

In [40]:
with open(os.path.join(BASE_DIR, "results/xgboost_model/best_params_stock.json"), "r") as f:
    best_xgboost_stock_params = json.load(f)

In [42]:
int_xgboost_params = [
    "max_depth",
    "n_estimators",
    "min_child_weight"
]

for p in int_xgboost_params:
    best_xgboost_stock_params[p] = int(best_xgboost_stock_params[p])

In [43]:
xgboost_stock_model = XGBoostRegressionModel(params=best_xgboost_stock_params)

with open(pickle_model_stock_paths["xgboost_model_stock"], "wb") as file: 
    pickle.dump(xgboost_stock_model, file)

In [44]:
with open(pickle_model_stock_paths["xgboost_model_stock"], "rb") as file: 
    xgboost_stock_v2 = pickle.load(file)

In [45]:
wf = WalkForwardValidator(
    feature_matrix=feature_matrix_stock,
    model=xgboost_stock_v2,
    validation_start="2025-07-01",
    validation_end="2026-12-31",
    rebalance_date=1,
    min_train_size=25000,
)

X_test, test_preds = wf.run_data()

daily_ic = test_preds.groupby("Date").apply(
    lambda x: x["prediction"].corr(
        x["future_return_5d"],
        method="spearman",
    ),
    include_groups = False
)

mean_ic = daily_ic.dropna().mean()

In [46]:
mean_ic

np.float64(0.04539480966151561)

#### Decision Tree

In [18]:
DTTuner(20, 123, feature_matrix_market, "market").run_data()

/home/gordon1999/.local/lib/python3.10/site-packages/pandas/core/nanops.py:1632: ConstantInputWarning: An input array is constant; the correlation coefficient is not defined.
  return spearmanr(a, b)[0]

1/20: IC = 0.04503

/home/gordon1999/.local/lib/python3.10/site-packages/pandas/core/nanops.py:1632: ConstantInputWarning: An input array is constant; the correlation coefficient is not defined.
  return spearmanr(a, b)[0]

2/20: IC = -0.01880

/home/gordon1999/.local/lib/python3.10/site-packages/pandas/core/nanops.py:1632: ConstantInputWarning: An input array is constant; the correlation coefficient is not defined.
  return spearmanr(a, b)[0]

3/20: IC = 0.01777

/home/gordon1999/.local/lib/python3.10/site-packages/pandas/core/nanops.py:1632: ConstantInputWarning: An input array is constant; the correlation coefficient is not defined.
  return spearmanr(a, b)[0]

4/20: IC = 0.04503

/home/gordon1999/.local/lib/python3.10/site-packages/pandas/core/nanops.py:1632: ConstantInputWarning: An input array is constant; the correlation coefficient is not defined.
  return spearmanr(a, b)[0]

5/20: IC = 0.03030

/home/gordon1999/.local/lib/python3.10/site-packages/pandas/core/nanops.py:1632: ConstantInputWarning: An input array is constant; the correlation coefficient is not defined.
  return spearmanr(a, b)[0]

6/20: IC = -0.02229

/home/gordon1999/.local/lib/python3.10/site-packages/pandas/core/nanops.py:1632: ConstantInputWarning: An input array is constant; the correlation coefficient is not defined.
  return spearmanr(a, b)[0]

7/20: IC = 0.02608

/home/gordon1999/.local/lib/python3.10/site-packages/pandas/core/nanops.py:1632: ConstantInputWarning: An input array is constant; the correlation coefficient is not defined.
  return spearmanr(a, b)[0]

8/20: IC = 0.00303

/home/gordon1999/.local/lib/python3.10/site-packages/pandas/core/nanops.py:1632: ConstantInputWarning: An input array is constant; the correlation coefficient is not defined.
  return spearmanr(a, b)[0]

9/20: IC = 0.02206

/home/gordon1999/.local/lib/python3.10/site-packages/pandas/core/nanops.py:1632: ConstantInputWarning: An input array is constant; the correlation coefficient is not defined.
  return spearmanr(a, b)[0]

10/20: IC = 0.00032

/home/gordon1999/.local/lib/python3.10/site-packages/pandas/core/nanops.py:1632: ConstantInputWarning: An input array is constant; the correlation coefficient is not defined.
  return spearmanr(a, b)[0]

11/20: IC = 0.03189

/home/gordon1999/.local/lib/python3.10/site-packages/pandas/core/nanops.py:1632: ConstantInputWarning: An input array is constant; the correlation coefficient is not defined.
  return spearmanr(a, b)[0]

12/20: IC = -0.00433

/home/gordon1999/.local/lib/python3.10/site-packages/pandas/core/nanops.py:1632: ConstantInputWarning: An input array is constant; the correlation coefficient is not defined.
  return spearmanr(a, b)[0]

13/20: IC = 0.02254

/home/gordon1999/.local/lib/python3.10/site-packages/pandas/core/nanops.py:1632: ConstantInputWarning: An input array is constant; the correlation coefficient is not defined.
  return spearmanr(a, b)[0]

14/20: IC = 0.03049

/home/gordon1999/.local/lib/python3.10/site-packages/pandas/core/nanops.py:1632: ConstantInputWarning: An input array is constant; the correlation coefficient is not defined.
  return spearmanr(a, b)[0]

15/20: IC = 0.00578

/home/gordon1999/.local/lib/python3.10/site-packages/pandas/core/nanops.py:1632: ConstantInputWarning: An input array is constant; the correlation coefficient is not defined.
  return spearmanr(a, b)[0]

16/20: IC = 0.02540

/home/gordon1999/.local/lib/python3.10/site-packages/pandas/core/nanops.py:1632: ConstantInputWarning: An input array is constant; the correlation coefficient is not defined.
  return spearmanr(a, b)[0]

17/20: IC = 0.00578

/home/gordon1999/.local/lib/python3.10/site-packages/pandas/core/nanops.py:1632: ConstantInputWarning: An input array is constant; the correlation coefficient is not defined.
  return spearmanr(a, b)[0]

18/20: IC = 0.00667

/home/gordon1999/.local/lib/python3.10/site-packages/pandas/core/nanops.py:1632: ConstantInputWarning: An input array is constant; the correlation coefficient is not defined.
  return spearmanr(a, b)[0]

19/20: IC = 0.00011
20/20: IC = -0.01785

/home/gordon1999/.local/lib/python3.10/site-packages/pandas/core/nanops.py:1632: ConstantInputWarning: An input array is constant; the correlation coefficient is not defined.
  return spearmanr(a, b)[0]

In [19]:
results_dt_market_df = pd.read_csv(os.path.join(BASE_DIR, "results/dt_model/random_search_market.csv"))
results_dt_market_df.head()

   max_depth  min_samples_split  min_samples_leaf  max_features   mean_ic
0          2                 50                10           0.5  0.045031
1          2                 20                10           0.5  0.045031
2          6                 50                20           0.5  0.031889
3          6                100                20           NaN  0.030488
4          6                 50                50           NaN  0.030304

In [21]:
with open(os.path.join(BASE_DIR, "results/dt_model/best_params_market.json"), "r") as f:
    best_dt_market_params = json.load(f)

In [22]:
int_dt_params = [
    "max_depth",
    "min_samples_split",
    "min_samples_leaf"
]

for p in int_dt_params:
    best_dt_market_params[p] = int(best_dt_market_params[p])

In [31]:
dt_market_model = DTRegressionModel(params=best_dt_market_params)

with open(pickle_model_market_paths["dt_model_market"], "wb") as file: 
    pickle.dump(dt_market_model, file)

In [33]:
with open(pickle_model_market_paths["dt_model_market"], "rb") as file: 
    dt_market_v2 = pickle.load(file)

In [34]:
wf = WalkForwardValidator(
    feature_matrix=feature_matrix_market,
    model=dt_market_v2,
    validation_start="2025-07-01",
    validation_end="2026-12-31",
    rebalance_date=1,
    min_train_size=25000,
)

X_test, test_preds = wf.run_data()

daily_ic = test_preds.groupby("Date").apply(
    lambda x: x["prediction"].corr(
        x["future_return_5d"],
        method="spearman",
    ),
    include_groups = False
)

mean_ic = daily_ic.dropna().mean()

/home/gordon1999/.local/lib/python3.10/site-packages/pandas/core/nanops.py:1632: ConstantInputWarning: An input array is constant; the correlation coefficient is not defined.
  return spearmanr(a, b)[0]

In [36]:
mean_ic

np.float64(0.03680510430828885)

In [7]:
LightGBMTuner(20, 42, feature_matrix_market, "market").run_data()

1/20: IC = 0.02249
2/20: IC = 0.01671
3/20: IC = 0.01870
4/20: IC = 0.01123
5/20: IC = 0.03230
6/20: IC = -0.00142
7/20: IC = 0.01079
8/20: IC = 0.02340
9/20: IC = -0.00420
10/20: IC = 0.00152
11/20: IC = 0.02322
12/20: IC = -0.00587
13/20: IC = 0.00578
14/20: IC = -0.00160
15/20: IC = 0.00499
16/20: IC = 0.02379
17/20: IC = -0.00287
18/20: IC = 0.00908
19/20: IC = -0.00085
20/20: IC = -0.00050

In [8]:
results_lightgbm_market_df = pd.read_csv(os.path.join(BASE_DIR, "results/lightgbm_model/random_search_market.csv"))
results_lightgbm_market_df.head()

,learning_rate,num_leaves,max_depth,n_estimators,min_child_samples,mean_ic
0,0.02,63,9,100,20,0.032295
1,0.01,31,5,300,100,0.023795
2,0.04,63,9,100,100,0.023400
3,0.02,63,5,200,10,0.023225
4,0.01,31,9,200,20,0.022490

In [10]:
with open(os.path.join(BASE_DIR, "results/lightgbm_model/best_params_market.json"), "r") as f:
    best_lightgbm_market_params = json.load(f)

In [11]:
int_lightgbm_params = [
    "num_leaves",
    "max_depth",
    "n_estimators",
    "min_child_samples",
]

for p in int_lightgbm_params:
    best_lightgbm_market_params[p] = int(best_lightgbm_market_params[p])

In [13]:
lightgbm_market_model = LightGBMRegressionModel(params=best_lightgbm_market_params)

with open(pickle_model_market_paths["lightgbm_model_market"], "wb") as file: 
    pickle.dump(lightgbm_market_model, file)

In [16]:
with open(pickle_model_market_paths["lightgbm_model_market"], "rb") as file: 
    lightgbm_market_v2 = pickle.load(file)

In [17]:
wf = WalkForwardValidator(
    feature_matrix=feature_matrix_market,
    model=lightgbm_market_v2,
    validation_start="2025-07-01",
    validation_end="2026-12-31",
    rebalance_date=1,
    min_train_size=25000,
)

X_test, test_preds = wf.run_data()

daily_ic = test_preds.groupby("Date").apply(
    lambda x: x["prediction"].corr(
        x["future_return_5d"],
        method="spearman",
    ),
    include_groups = False
)

mean_ic = daily_ic.dropna().mean()

In [18]:
mean_ic

np.float64(0.017541027526196136)

In [21]:
XGBoostTuner(20, 42, feature_matrix_market, "market").run_data()

1/20: IC = 0.01563
2/20: IC = 0.01879
3/20: IC = 0.00135

/home/gordon1999/.local/lib/python3.10/site-packages/pandas/core/nanops.py:1632: ConstantInputWarning: An input array is constant; the correlation coefficient is not defined.
  return spearmanr(a, b)[0]

4/20: IC = 0.01874
5/20: IC = 0.01256
6/20: IC = 0.00524
7/20: IC = -0.00381
8/20: IC = -0.01135
9/20: IC = 0.01049
10/20: IC = 0.02470
11/20: IC = 0.00067
12/20: IC = 0.01368
13/20: IC = 0.01004
14/20: IC = 0.00376
15/20: IC = 0.00328
16/20: IC = 0.00454
17/20: IC = 0.00748
18/20: IC = 0.01195
19/20: IC = 0.01074
20/20: IC = 0.01308

In [25]:
results_xgboost_market_df = pd.read_csv(os.path.join(BASE_DIR, "results/xgboost_model/random_searchmarket.csv"))
results_xgboost_market_df.head()

   learning_rate  max_depth  n_estimators  min_child_weight   mean_ic
0           0.01          3           500                10  0.024702
1           0.02          4           200                10  0.018790
2           0.01          3           100                20  0.018744
3           0.20          3           100                50  0.015628
4           0.20          6           100               100  0.013683

In [26]:
with open(os.path.join(BASE_DIR, "results/xgboost_model/best_params_market.json"), "r") as f:
    best_xgboost_market_params = json.load(f)

In [27]:
int_xgboost_params = [
    "max_depth",
    "n_estimators",
    "min_child_weight"
]

for p in int_xgboost_params:
    best_xgboost_market_params[p] = int(best_xgboost_market_params[p])

In [29]:
xgboost_market_model = XGBoostRegressionModel(params=best_xgboost_market_params)

with open(pickle_model_market_paths["xgboost_model_market"], "wb") as file: 
    pickle.dump(xgboost_market_model, file)

In [30]:
with open(pickle_model_market_paths["xgboost_model_market"], "rb") as file: 
    xgboost_market_v2 = pickle.load(file)

In [31]:
wf = WalkForwardValidator(
    feature_matrix=feature_matrix_market,
    model=xgboost_market_v2,
    validation_start="2025-07-01",
    validation_end="2026-12-31",
    rebalance_date=1,
    min_train_size=25000,
)

X_test, test_preds = wf.run_data()

daily_ic = test_preds.groupby("Date").apply(
    lambda x: x["prediction"].corr(
        x["future_return_5d"],
        method="spearman",
    ),
    include_groups = False
)

mean_ic = daily_ic.dropna().mean()

In [32]:
mean_ic

np.float64(0.05022851288994176)

DTTuner(20, 123, feature_matrix_market, "market").run_data()

In [28]:
DTTuner(20, 123, feature_matrix_macro_market, "macro_market").run_data()

/home/gordon1999/.local/lib/python3.10/site-packages/pandas/core/nanops.py:1632: ConstantInputWarning: An input array is constant; the correlation coefficient is not defined.
  return spearmanr(a, b)[0]

1/20: IC = -0.03324

/home/gordon1999/.local/lib/python3.10/site-packages/pandas/core/nanops.py:1632: ConstantInputWarning: An input array is constant; the correlation coefficient is not defined.
  return spearmanr(a, b)[0]

2/20: IC = -0.03457

/home/gordon1999/.local/lib/python3.10/site-packages/pandas/core/nanops.py:1632: ConstantInputWarning: An input array is constant; the correlation coefficient is not defined.
  return spearmanr(a, b)[0]

3/20: IC = 0.01215

/home/gordon1999/.local/lib/python3.10/site-packages/pandas/core/nanops.py:1632: ConstantInputWarning: An input array is constant; the correlation coefficient is not defined.
  return spearmanr(a, b)[0]

4/20: IC = -0.03324

/home/gordon1999/.local/lib/python3.10/site-packages/pandas/core/nanops.py:1632: ConstantInputWarning: An input array is constant; the correlation coefficient is not defined.
  return spearmanr(a, b)[0]

5/20: IC = -0.00789

/home/gordon1999/.local/lib/python3.10/site-packages/pandas/core/nanops.py:1632: ConstantInputWarning: An input array is constant; the correlation coefficient is not defined.
  return spearmanr(a, b)[0]

6/20: IC = -0.04665

/home/gordon1999/.local/lib/python3.10/site-packages/pandas/core/nanops.py:1632: ConstantInputWarning: An input array is constant; the correlation coefficient is not defined.
  return spearmanr(a, b)[0]

7/20: IC = -0.00863

/home/gordon1999/.local/lib/python3.10/site-packages/pandas/core/nanops.py:1632: ConstantInputWarning: An input array is constant; the correlation coefficient is not defined.
  return spearmanr(a, b)[0]

8/20: IC = -0.05696

/home/gordon1999/.local/lib/python3.10/site-packages/pandas/core/nanops.py:1632: ConstantInputWarning: An input array is constant; the correlation coefficient is not defined.
  return spearmanr(a, b)[0]

9/20: IC = -0.02962

/home/gordon1999/.local/lib/python3.10/site-packages/pandas/core/nanops.py:1632: ConstantInputWarning: An input array is constant; the correlation coefficient is not defined.
  return spearmanr(a, b)[0]

10/20: IC = -0.07937

/home/gordon1999/.local/lib/python3.10/site-packages/pandas/core/nanops.py:1632: ConstantInputWarning: An input array is constant; the correlation coefficient is not defined.
  return spearmanr(a, b)[0]

11/20: IC = 0.00596

/home/gordon1999/.local/lib/python3.10/site-packages/pandas/core/nanops.py:1632: ConstantInputWarning: An input array is constant; the correlation coefficient is not defined.
  return spearmanr(a, b)[0]

12/20: IC = -0.02933

/home/gordon1999/.local/lib/python3.10/site-packages/pandas/core/nanops.py:1632: ConstantInputWarning: An input array is constant; the correlation coefficient is not defined.
  return spearmanr(a, b)[0]

13/20: IC = -0.04014

/home/gordon1999/.local/lib/python3.10/site-packages/pandas/core/nanops.py:1632: ConstantInputWarning: An input array is constant; the correlation coefficient is not defined.
  return spearmanr(a, b)[0]

14/20: IC = -0.00409

/home/gordon1999/.local/lib/python3.10/site-packages/pandas/core/nanops.py:1632: ConstantInputWarning: An input array is constant; the correlation coefficient is not defined.
  return spearmanr(a, b)[0]

15/20: IC = -0.00158

/home/gordon1999/.local/lib/python3.10/site-packages/pandas/core/nanops.py:1632: ConstantInputWarning: An input array is constant; the correlation coefficient is not defined.
  return spearmanr(a, b)[0]

16/20: IC = -0.00934

/home/gordon1999/.local/lib/python3.10/site-packages/pandas/core/nanops.py:1632: ConstantInputWarning: An input array is constant; the correlation coefficient is not defined.
  return spearmanr(a, b)[0]

17/20: IC = -0.00158

/home/gordon1999/.local/lib/python3.10/site-packages/pandas/core/nanops.py:1632: ConstantInputWarning: An input array is constant; the correlation coefficient is not defined.
  return spearmanr(a, b)[0]

18/20: IC = -0.05167

/home/gordon1999/.local/lib/python3.10/site-packages/pandas/core/nanops.py:1632: ConstantInputWarning: An input array is constant; the correlation coefficient is not defined.
  return spearmanr(a, b)[0]

19/20: IC = -0.07949
20/20: IC = -0.03536

/home/gordon1999/.local/lib/python3.10/site-packages/pandas/core/nanops.py:1632: ConstantInputWarning: An input array is constant; the correlation coefficient is not defined.
  return spearmanr(a, b)[0]

In [29]:
results_dt_macro_market_df = pd.read_csv(os.path.join(BASE_DIR, "results/dt_model/random_search_macro_market.csv"))
results_dt_macro_market_df.head()

   max_depth  min_samples_split  min_samples_leaf  max_features   mean_ic
0          6                100                20           0.5  0.012149
1          6                 50                20           0.5  0.005963
2          5                100                50           0.5 -0.001580
3          5                100                50           0.5 -0.001580
4          6                100                20           NaN -0.004089

In [30]:
with open(os.path.join(BASE_DIR, "results/dt_model/best_params_macro_market.json"), "r") as f:
    best_dt_macro_market_params = json.load(f)

In [40]:
int_dt_params = [
    "max_depth",
    "min_samples_split",
    "min_samples_leaf"
]

for p in int_dt_params:
    best_dt_macro_market_params[p] = int(best_dt_macro_market_params[p])

In [44]:
dt_macro_market_model = DTRegressionModel(params=best_dt_macro_market_params)

with open(pickle_model_macro_market_paths["dt_model_macro_market"], "wb") as file: 
    pickle.dump(dt_macro_market_model, file)

In [45]:
with open(pickle_model_macro_market_paths["dt_model_macro_market"], "rb") as file: 
    dt_macro_market_v2 = pickle.load(file)

In [46]:
wf = WalkForwardValidator(
    feature_matrix=feature_matrix_macro_market,
    model=dt_macro_market_v2,
    validation_start="2025-07-01",
    validation_end="2026-12-31",
    rebalance_date=1,
    min_train_size=25000,
)

X_test, test_preds = wf.run_data()

daily_ic = test_preds.groupby("Date").apply(
    lambda x: x["prediction"].corr(
        x["future_return_5d"],
        method="spearman",
    ),
    include_groups = False
)

mean_ic = daily_ic.dropna().mean()

/home/gordon1999/.local/lib/python3.10/site-packages/pandas/core/nanops.py:1632: ConstantInputWarning: An input array is constant; the correlation coefficient is not defined.
  return spearmanr(a, b)[0]

In [47]:
mean_ic

np.float64(0.019320281953072903)

#### LightGBM

In [20]:
LightGBMTuner(20, 42, feature_matrix_macro_market, "macro_market").run_data()

1/20: IC = -0.00853
2/20: IC = 0.00403
3/20: IC = -0.00470
4/20: IC = -0.00893
5/20: IC = -0.02606
6/20: IC = -0.01282
7/20: IC = -0.00303
8/20: IC = -0.00987
9/20: IC = -0.00954
10/20: IC = -0.01549
11/20: IC = -0.01249
12/20: IC = -0.00755
13/20: IC = -0.01469
14/20: IC = -0.00308
15/20: IC = -0.01732
16/20: IC = -0.00942
17/20: IC = -0.00974
18/20: IC = -0.01244
19/20: IC = -0.01017
20/20: IC = 0.00313

In [33]:
results_lightgbm_macro_market_df = pd.read_csv(os.path.join(BASE_DIR, "results/lightgbm_model/random_search_macro_market.csv"))
results_lightgbm_macro_market_df.head()

,learning_rate,num_leaves,max_depth,n_estimators,min_child_samples,mean_ic
0,0.02,127,5,100,100,0.004035
1,0.04,31,7,500,10,0.003135
2,0.04,31,5,500,10,-0.003029
3,0.10,127,7,200,20,-0.003081
4,0.01,31,5,200,20,-0.004695

In [34]:
with open(os.path.join(BASE_DIR, "results/lightgbm_model/best_params_macro_market.json"), "r") as f:
    best_lightgbm_macro_market_params = json.load(f)

In [35]:
int_lightgbm_params = [
    "num_leaves",
    "max_depth",
    "n_estimators",
    "min_child_samples",
]

for p in int_lightgbm_params:
    best_lightgbm_macro_market_params[p] = int(best_lightgbm_macro_market_params[p])

In [39]:
lightgbm_macro_market_model = LightGBMRegressionModel(params=best_lightgbm_macro_market_params)

with open(pickle_model_macro_market_paths["lightgbm_model_macro_market"], "wb") as file: 
    pickle.dump(lightgbm_macro_market_model, file)

In [40]:
with open(pickle_model_macro_market_paths["lightgbm_model_macro_market"], "rb") as file: 
    lightgbm_macro_market_v2 = pickle.load(file)

In [41]:
wf = WalkForwardValidator(
    feature_matrix=feature_matrix_macro_market,
    model=lightgbm_macro_market_v2,
    validation_start="2025-07-01",
    validation_end="2026-12-31",
    rebalance_date=1,
    min_train_size=25000,
)

X_test, test_preds = wf.run_data()

daily_ic = test_preds.groupby("Date").apply(
    lambda x: x["prediction"].corr(
        x["future_return_5d"],
        method="spearman",
    ),
    include_groups = False
)

mean_ic = daily_ic.dropna().mean()

In [42]:
mean_ic

np.float64(0.05662860632913941)

In [22]:
XGBoostTuner(20, 42, feature_matrix_macro_market, "macro_market").run_data()

1/20: IC = 0.01260
2/20: IC = -0.00618
3/20: IC = -0.01592

/home/gordon1999/.local/lib/python3.10/site-packages/pandas/core/nanops.py:1632: ConstantInputWarning: An input array is constant; the correlation coefficient is not defined.
  return spearmanr(a, b)[0]

4/20: IC = -0.00806
5/20: IC = -0.02053
6/20: IC = 0.00458
7/20: IC = -0.00391
8/20: IC = -0.01012
9/20: IC = -0.00763
10/20: IC = -0.00602
11/20: IC = -0.00055
12/20: IC = -0.00787
13/20: IC = -0.01575
14/20: IC = -0.00021
15/20: IC = -0.00984
16/20: IC = 0.00280
17/20: IC = -0.00521
18/20: IC = -0.00605
19/20: IC = 0.00033
20/20: IC = -0.00066

In [45]:
results_xgboost_macro_market_df = pd.read_csv(os.path.join(BASE_DIR, "results/xgboost_model/random_searchmacro_market.csv"))
results_xgboost_macro_market_df.head()

   learning_rate  max_depth  n_estimators  min_child_weight   mean_ic
0            0.2          3           100                50  0.012600
1            0.2          7           500                20  0.004576
2            0.3          4           100               100  0.002805
3            0.2          3           200                20  0.000329
4            0.1          4           100                10 -0.000213

In [46]:
with open(os.path.join(BASE_DIR, "results/xgboost_model/best_params_macro_market.json"), "r") as f:
    best_xgboost_macro_market_params = json.load(f)

In [47]:
int_xgboost_params = [
    "max_depth",
    "n_estimators",
    "min_child_weight"
]

for p in int_xgboost_params:
    best_xgboost_macro_market_params[p] = int(best_xgboost_macro_market_params[p])

In [48]:
xgboost_macro_market_model = XGBoostRegressionModel(params=best_xgboost_macro_market_params)

with open(pickle_model_macro_market_paths["xgboost_model_macro_market"], "wb") as file: 
    pickle.dump(xgboost_macro_market_model, file)

In [49]:
with open(pickle_model_macro_market_paths["xgboost_model_macro_market"], "rb") as file: 
    xgboost_macro_market_v2 = pickle.load(file)

In [50]:
wf = WalkForwardValidator(
    feature_matrix=feature_matrix_macro_market,
    model=xgboost_macro_market_v2,
    validation_start="2025-07-01",
    validation_end="2026-12-31",
    rebalance_date=1,
    min_train_size=25000,
)

X_test, test_preds = wf.run_data()

daily_ic = test_preds.groupby("Date").apply(
    lambda x: x["prediction"].corr(
        x["future_return_5d"],
        method="spearman",
    ),
    include_groups = False
)

mean_ic = daily_ic.dropna().mean()

In [51]:
mean_ic

np.float64(0.03967915543911888)

#### Gated Recurrent Unit

In [5]:
GRUTuner(6, 42, feature_matrix_stock).run_data()

TensorFlow GPU: using /physical_device:GPU:0
GRU fold 1/103 2023-07-04: skipped (train=1880, test=188, reason=train_too_small)
GRU fold 2/103 2023-07-11: skipped (train=2820, test=188, reason=train_too_small)
GRU fold 3/103 2023-07-18: skipped (train=3760, test=188, reason=train_too_small)
GRU fold 4/103 2023-07-25: skipped (train=4700, test=188, reason=train_too_small)
GRU fold 5/103 2023-08-01: skipped (train=5640, test=189, reason=train_too_small)
GRU fold 6/103 2023-08-08: skipped (train=6581, test=189, reason=train_too_small)
GRU fold 7/103 2023-08-15: skipped (train=7526, test=189, reason=train_too_small)
GRU fold 8/103 2023-08-22: skipped (train=8471, test=189, reason=train_too_small)
GRU fold 9/103 2023-08-29: skipped (train=9416, test=189, reason=train_too_small)
GRU fold 10/103 2023-09-05: fresh training (train=10361, test=189)

I0000 00:00:1783429756.400885   20194 gpu_device.cc:2043] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 5590 MB memory:  -> device: 0, name: NVIDIA GeForce RTX 3060 Ti, pci bus id: 0000:01:00.0, compute capability: 8.6
I0000 00:00:1783429757.602859   20379 cuda_dnn.cc:461] Loaded cuDNN version 92400

ListNet epoch 1/10: loss = 5.244968
ListNet epoch 2/10: loss = 5.250819
ListNet epoch 3/10: loss = 5.268196
ListNet epoch 4/10: loss = 5.204166
ListNet epoch 5/10: loss = 5.168419
ListNet epoch 6/10: loss = 5.082496
ListNet epoch 7/10: loss = 5.089852
ListNet epoch 8/10: loss = 5.004738
ListNet epoch 9/10: loss = 4.943456
ListNet epoch 10/10: loss = 4.882118
GRU fold 11/103 2023-09-12: fine-tune training (train=11306, test=189)
ListNet epoch 1/2: loss = 4.903396
ListNet epoch 2/2: loss = 4.936039
GRU fold 12/103 2023-09-19: fine-tune training (train=12251, test=189)
ListNet epoch 1/2: loss = 4.806054
ListNet epoch 2/2: loss = 4.792139
GRU fold 13/103 2023-09-26: fine-tune training (train=13196, test=189)
ListNet epoch 1/2: loss = 4.758044
ListNet epoch 2/2: loss = 4.765497
GRU fold 14/103 2023-10-03: fine-tune training (train=14141, test=189)
ListNet epoch 1/2: loss = 4.849443
ListNet epoch 2/2: loss = 4.975499
GRU fold 15/103 2023-10-10: fine-tune training (train=15086, test=190)
ListNet epoch 1/2: loss = 4.704010
ListNet epoch 2/2: loss = 4.785132
GRU fold 16/103 2023-10-17: fine-tune training (train=16032, test=190)
ListNet epoch 1/2: loss = 4.874240
ListNet epoch 2/2: loss = 4.676294
GRU fold 17/103 2023-10-24: fine-tune training (train=16982, test=190)
ListNet epoch 1/2: loss = 4.736001
ListNet epoch 2/2: loss = 4.739176
GRU fold 18/103 2023-10-31: fine-tune training (train=17932, test=191)
ListNet epoch 1/2: loss = 4.611518
ListNet epoch 2/2: loss = 4.555229
GRU fold 19/103 2023-11-07: fine-tune training (train=18885, test=191)
ListNet epoch 1/2: loss = 4.592342
ListNet epoch 2/2: loss = 4.619865
GRU fold 20/103 2023-11-14: fine-tune training (train=19840, test=191)
ListNet epoch 1/2: loss = 4.670038
ListNet epoch 2/2: loss = 4.646261
GRU fold 21/103 2023-11-21: fine-tune training (train=20795, test=191)
ListNet epoch 1/2: loss = 4.701995
ListNet epoch 2/2: loss = 4.597828
GRU fold 22/103 2023-11-28: fine-tune training (train=21750, test=191)
ListNet epoch 1/2: loss = 4.640144
ListNet epoch 2/2: loss = 4.630887
GRU fold 23/103 2023-12-05: fine-tune training (train=22705, test=191)
ListNet epoch 1/2: loss = 4.475839
ListNet epoch 2/2: loss = 4.523083
GRU fold 24/103 2023-12-12: fine-tune training (train=23660, test=191)
ListNet epoch 1/2: loss = 4.531662
ListNet epoch 2/2: loss = 4.636855
GRU fold 25/103 2023-12-19: fine-tune training (train=24615, test=191)
ListNet epoch 1/2: loss = 4.585577
ListNet epoch 2/2: loss = 4.732181
GRU fold 26/103 2024-01-02: fine-tune training (train=25952, test=191)
ListNet epoch 1/2: loss = 4.737717
ListNet epoch 2/2: loss = 4.550378
GRU fold 27/103 2024-01-09: fine-tune training (train=26907, test=191)
ListNet epoch 1/2: loss = 4.601207
ListNet epoch 2/2: loss = 4.662367
GRU fold 28/103 2024-01-16: fine-tune training (train=27862, test=191)
ListNet epoch 1/2: loss = 4.608223
ListNet epoch 2/2: loss = 4.535583
GRU fold 29/103 2024-01-23: fine-tune training (train=28817, test=191)
ListNet epoch 1/2: loss = 4.574404
ListNet epoch 2/2: loss = 4.467043
GRU fold 30/103 2024-01-30: fine-tune training (train=29581, test=191)
ListNet epoch 1/2: loss = 4.534371
ListNet epoch 2/2: loss = 4.423629
GRU fold 31/103 2024-02-06: fine-tune training (train=30536, test=191)
ListNet epoch 1/2: loss = 4.446868
ListNet epoch 2/2: loss = 4.402436
GRU fold 32/103 2024-02-13: fine-tune training (train=31491, test=191)
ListNet epoch 1/2: loss = 4.436867
ListNet epoch 2/2: loss = 4.413900
GRU fold 33/103 2024-02-20: fine-tune training (train=32446, test=191)
ListNet epoch 1/2: loss = 4.793243
ListNet epoch 2/2: loss = 4.500219
GRU fold 34/103 2024-02-27: fine-tune training (train=33401, test=191)
ListNet epoch 1/2: loss = 4.553396
ListNet epoch 2/2: loss = 4.574336
GRU fold 35/103 2024-03-05: fine-tune training (train=34356, test=191)
ListNet epoch 1/2: loss = 4.411919
ListNet epoch 2/2: loss = 4.600533
GRU fold 36/103 2024-03-12: fresh training (train=35311, test=191)
ListNet epoch 1/10: loss = 5.251627
ListNet epoch 2/10: loss = 5.238837
ListNet epoch 3/10: loss = 5.167126
ListNet epoch 4/10: loss = 5.040985
ListNet epoch 5/10: loss = 4.962173
ListNet epoch 6/10: loss = 4.829698
ListNet epoch 7/10: loss = 4.805086
ListNet epoch 8/10: loss = 4.733713
ListNet epoch 9/10: loss = 4.715675
ListNet epoch 10/10: loss = 4.640169
GRU fold 37/103 2024-03-19: fine-tune training (train=36266, test=191)
ListNet epoch 1/2: loss = 4.679309
ListNet epoch 2/2: loss = 4.574188
GRU fold 38/103 2024-03-26: fine-tune training (train=37221, test=191)
ListNet epoch 1/2: loss = 4.629000
ListNet epoch 2/2: loss = 4.532346
GRU fold 39/103 2024-04-02: fine-tune training (train=37794, test=191)
ListNet epoch 1/2: loss = 4.591398
ListNet epoch 2/2: loss = 4.601016
GRU fold 40/103 2024-04-09: fine-tune training (train=38749, test=192)
ListNet epoch 1/2: loss = 4.535134
ListNet epoch 2/2: loss = 4.469401
GRU fold 41/103 2024-04-16: fine-tune training (train=39706, test=192)
ListNet epoch 1/2: loss = 4.801208
ListNet epoch 2/2: loss = 4.481735
GRU fold 42/103 2024-04-23: fine-tune training (train=40666, test=192)
ListNet epoch 1/2: loss = 4.486936
ListNet epoch 2/2: loss = 4.550998
GRU fold 43/103 2024-04-30: fine-tune training (train=41434, test=192)
ListNet epoch 1/2: loss = 4.554003
ListNet epoch 2/2: loss = 4.630282
GRU fold 44/103 2024-05-07: fine-tune training (train=42394, test=192)
ListNet epoch 1/2: loss = 4.544349
ListNet epoch 2/2: loss = 4.541282
GRU fold 45/103 2024-05-14: fine-tune training (train=43354, test=192)
ListNet epoch 1/2: loss = 4.508461
ListNet epoch 2/2: loss = 4.476710
GRU fold 46/103 2024-05-21: fine-tune training (train=44314, test=192)
ListNet epoch 1/2: loss = 4.428719
ListNet epoch 2/2: loss = 4.498246
GRU fold 47/103 2024-05-28: fine-tune training (train=45274, test=192)
ListNet epoch 1/2: loss = 4.596852
ListNet epoch 2/2: loss = 4.618473
GRU fold 48/103 2024-06-04: fine-tune training (train=46234, test=192)
ListNet epoch 1/2: loss = 4.593608
ListNet epoch 2/2: loss = 4.584290
GRU fold 49/103 2024-06-11: fine-tune training (train=47002, test=192)
ListNet epoch 1/2: loss = 4.828546
ListNet epoch 2/2: loss = 4.552436
GRU fold 50/103 2024-06-18: fine-tune training (train=47962, test=192)
ListNet epoch 1/2: loss = 4.590212
ListNet epoch 2/2: loss = 4.457191
GRU fold 51/103 2024-06-25: fine-tune training (train=48922, test=193)
ListNet epoch 1/2: loss = 4.560325
ListNet epoch 2/2: loss = 4.526568
GRU fold 52/103 2024-07-02: fine-tune training (train=49886, test=193)
ListNet epoch 1/2: loss = 4.440324
ListNet epoch 2/2: loss = 4.506681
GRU fold 53/103 2024-07-09: fine-tune training (train=50851, test=193)
ListNet epoch 1/2: loss = 4.432629
ListNet epoch 2/2: loss = 4.421058
GRU fold 54/103 2024-07-16: fine-tune training (train=51816, test=193)
ListNet epoch 1/2: loss = 4.689616
ListNet epoch 2/2: loss = 4.576821
GRU fold 55/103 2024-07-23: fine-tune training (train=52781, test=193)
ListNet epoch 1/2: loss = 4.529237
ListNet epoch 2/2: loss = 4.446419
GRU fold 56/103 2024-07-30: fine-tune training (train=53746, test=194)
ListNet epoch 1/2: loss = 4.429254
ListNet epoch 2/2: loss = 4.478011
GRU fold 57/103 2024-08-06: fine-tune training (train=54716, test=194)
ListNet epoch 1/2: loss = 4.506002
ListNet epoch 2/2: loss = 4.418733
GRU fold 58/103 2024-08-13: fine-tune training (train=55686, test=194)
ListNet epoch 1/2: loss = 4.372771
ListNet epoch 2/2: loss = 4.463423
GRU fold 59/103 2024-08-20: fine-tune training (train=56656, test=194)
ListNet epoch 1/2: loss = 4.423251
ListNet epoch 2/2: loss = 4.415889
GRU fold 60/103 2024-08-27: fine-tune training (train=57626, test=194)
ListNet epoch 1/2: loss = 4.492848
ListNet epoch 2/2: loss = 4.308773
GRU fold 61/103 2024-09-03: fine-tune training (train=58596, test=194)
ListNet epoch 1/2: loss = 4.497528
ListNet epoch 2/2: loss = 4.474539
GRU fold 62/103 2024-09-10: fresh training (train=59566, test=194)
ListNet epoch 1/10: loss = 5.273628
ListNet epoch 2/10: loss = 5.239996
ListNet epoch 3/10: loss = 5.084534
ListNet epoch 4/10: loss = 4.887985
ListNet epoch 5/10: loss = 4.698041
ListNet epoch 6/10: loss = 4.638395
ListNet epoch 7/10: loss = 4.759257
ListNet epoch 8/10: loss = 4.680772
ListNet epoch 9/10: loss = 4.639509
Early stopping at epoch 9/10
GRU fold 63/103 2024-09-17: fine-tune training (train=60536, test=194)
ListNet epoch 1/2: loss = 4.582636
ListNet epoch 2/2: loss = 4.517472
GRU fold 64/103 2024-09-24: fine-tune training (train=61506, test=194)
ListNet epoch 1/2: loss = 4.585647
ListNet epoch 2/2: loss = 4.675585
GRU fold 65/103 2024-10-01: fine-tune training (train=62476, test=194)
ListNet epoch 1/2: loss = 4.530119
ListNet epoch 2/2: loss = 4.420133
GRU fold 66/103 2024-10-08: fine-tune training (train=63446, test=194)
ListNet epoch 1/2: loss = 4.567112
ListNet epoch 2/2: loss = 4.553028
GRU fold 67/103 2024-10-15: fine-tune training (train=64416, test=194)
ListNet epoch 1/2: loss = 4.466397
ListNet epoch 2/2: loss = 4.473268
GRU fold 68/103 2024-10-22: fine-tune training (train=65386, test=194)
ListNet epoch 1/2: loss = 4.569828
ListNet epoch 2/2: loss = 4.506057
GRU fold 69/103 2024-10-29: fine-tune training (train=66356, test=194)
ListNet epoch 1/2: loss = 4.488403
ListNet epoch 2/2: loss = 4.492141
GRU fold 70/103 2024-11-05: fine-tune training (train=67326, test=194)
ListNet epoch 1/2: loss = 4.679918
ListNet epoch 2/2: loss = 4.770482
GRU fold 71/103 2024-11-12: fine-tune training (train=68296, test=194)
ListNet epoch 1/2: loss = 4.686844
ListNet epoch 2/2: loss = 4.688838
GRU fold 72/103 2024-11-19: fine-tune training (train=69266, test=194)
ListNet epoch 1/2: loss = 4.771451
ListNet epoch 2/2: loss = 4.640955
GRU fold 73/103 2024-11-26: fine-tune training (train=70236, test=194)
ListNet epoch 1/2: loss = 4.838572
ListNet epoch 2/2: loss = 4.866982
GRU fold 74/103 2024-12-03: fine-tune training (train=71206, test=194)
ListNet epoch 1/2: loss = 4.734917
ListNet epoch 2/2: loss = 4.697553
GRU fold 75/103 2024-12-10: fine-tune training (train=72176, test=194)
ListNet epoch 1/2: loss = 4.641919
ListNet epoch 2/2: loss = 4.606314
GRU fold 76/103 2024-12-17: fine-tune training (train=73146, test=194)
ListNet epoch 1/2: loss = 4.706547
ListNet epoch 2/2: loss = 4.634947
GRU fold 77/103 2024-12-24: fine-tune training (train=74116, test=194)
ListNet epoch 1/2: loss = 4.724598
ListNet epoch 2/2: loss = 4.669046
GRU fold 78/103 2024-12-31: fine-tune training (train=74698, test=194)
ListNet epoch 1/2: loss = 4.756691
ListNet epoch 2/2: loss = 4.870370
GRU fold 79/103 2025-01-07: fine-tune training (train=75474, test=194)
ListNet epoch 1/2: loss = 4.667428
ListNet epoch 2/2: loss = 4.537406
GRU fold 80/103 2025-01-14: fine-tune training (train=76444, test=194)
ListNet epoch 1/2: loss = 4.651709
ListNet epoch 2/2: loss = 4.598204
GRU fold 81/103 2025-01-21: fine-tune training (train=77414, test=195)
ListNet epoch 1/2: loss = 4.811898
ListNet epoch 2/2: loss = 4.589273
GRU fold 82/103 2025-01-28: fine-tune training (train=78192, test=195)
ListNet epoch 1/2: loss = 4.625659
ListNet epoch 2/2: loss = 4.562330
GRU fold 83/103 2025-02-04: fine-tune training (train=79167, test=195)
ListNet epoch 1/2: loss = 4.825354
ListNet epoch 2/2: loss = 4.679120
GRU fold 84/103 2025-02-11: fine-tune training (train=80142, test=195)
ListNet epoch 1/2: loss = 4.713119
ListNet epoch 2/2: loss = 4.581154
GRU fold 85/103 2025-02-18: fine-tune training (train=81117, test=195)
ListNet epoch 1/2: loss = 4.583692
ListNet epoch 2/2: loss = 4.621684
GRU fold 86/103 2025-02-25: fine-tune training (train=82092, test=195)
ListNet epoch 1/2: loss = 4.507565
ListNet epoch 2/2: loss = 4.807585
GRU fold 87/103 2025-03-04: fine-tune training (train=83067, test=195)
ListNet epoch 1/2: loss = 4.550818
ListNet epoch 2/2: loss = 4.687712
GRU fold 88/103 2025-03-11: fresh training (train=84042, test=195)
ListNet epoch 1/10: loss = 5.272928
ListNet epoch 2/10: loss = 5.295194
ListNet epoch 3/10: loss = 5.267234
ListNet epoch 4/10: loss = 5.219239
ListNet epoch 5/10: loss = 5.175567
ListNet epoch 6/10: loss = 5.104731
ListNet epoch 7/10: loss = 5.023992
ListNet epoch 8/10: loss = 5.003027
ListNet epoch 9/10: loss = 4.941699
ListNet epoch 10/10: loss = 4.957103
GRU fold 89/103 2025-03-18: fine-tune training (train=85017, test=195)
ListNet epoch 1/2: loss = 4.914310
ListNet epoch 2/2: loss = 4.856670
GRU fold 90/103 2025-03-25: fine-tune training (train=85992, test=195)
ListNet epoch 1/2: loss = 4.891783
ListNet epoch 2/2: loss = 4.808965
GRU fold 91/103 2025-04-01: fine-tune training (train=86967, test=195)
ListNet epoch 1/2: loss = 4.803205
ListNet epoch 2/2: loss = 4.903253
GRU fold 92/103 2025-04-08: fine-tune training (train=87942, test=195)
ListNet epoch 1/2: loss = 4.763286
ListNet epoch 2/2: loss = 4.887645
GRU fold 93/103 2025-04-15: fine-tune training (train=88917, test=195)
ListNet epoch 1/2: loss = 4.841671
ListNet epoch 2/2: loss = 4.789910
GRU fold 94/103 2025-04-22: fine-tune training (train=89502, test=195)
ListNet epoch 1/2: loss = 4.779452
ListNet epoch 2/2: loss = 4.776040
GRU fold 95/103 2025-04-29: fine-tune training (train=90282, test=195)
ListNet epoch 1/2: loss = 4.827223
ListNet epoch 2/2: loss = 5.469087
GRU fold 96/103 2025-05-06: fine-tune training (train=91257, test=195)
ListNet epoch 1/2: loss = 4.917248
ListNet epoch 2/2: loss = 5.410903
GRU fold 97/103 2025-05-13: fine-tune training (train=92232, test=195)
ListNet epoch 1/2: loss = 4.831978
ListNet epoch 2/2: loss = 4.897242
GRU fold 98/103 2025-05-20: fine-tune training (train=93207, test=195)
ListNet epoch 1/2: loss = 4.807226
ListNet epoch 2/2: loss = 4.772181
GRU fold 99/103 2025-05-27: fine-tune training (train=94182, test=195)
ListNet epoch 1/2: loss = 4.904717
ListNet epoch 2/2: loss = 4.866753
GRU fold 100/103 2025-06-03: fine-tune training (train=95157, test=195)
ListNet epoch 1/2: loss = 4.893071
ListNet epoch 2/2: loss = 5.050729
GRU fold 101/103 2025-06-10: fine-tune training (train=95937, test=195)
ListNet epoch 1/2: loss = 4.901979
ListNet epoch 2/2: loss = 4.805147
GRU fold 102/103 2025-06-17: fine-tune training (train=96912, test=195)
ListNet epoch 1/2: loss = 4.908308
ListNet epoch 2/2: loss = 4.896910
GRU fold 103/103 2025-06-24: fine-tune training (train=97887, test=197)
ListNet epoch 1/2: loss = 4.936088
ListNet epoch 2/2: loss = 4.858604

/mnt/c/Users/Gordon Li/Desktop/systematic_project/scripts/models/gru/tune_gru.py:88: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  daily_ic = preds.groupby("Date").apply(

1/6: IC = 0.02033 (raw_ic=0.02033, trained_folds=94, skipped_folds=9, coverage=91.3%)
GRU fold 1/103 2023-07-04: skipped (train=1880, test=188, reason=train_too_small)
GRU fold 2/103 2023-07-11: skipped (train=2820, test=188, reason=train_too_small)
GRU fold 3/103 2023-07-18: skipped (train=3760, test=188, reason=train_too_small)
GRU fold 4/103 2023-07-25: skipped (train=4700, test=188, reason=train_too_small)
GRU fold 5/103 2023-08-01: skipped (train=5640, test=189, reason=train_too_small)
GRU fold 6/103 2023-08-08: skipped (train=6581, test=189, reason=train_too_small)
GRU fold 7/103 2023-08-15: skipped (train=7526, test=189, reason=train_too_small)
GRU fold 8/103 2023-08-22: skipped (train=8471, test=189, reason=train_too_small)
GRU fold 9/103 2023-08-29: skipped (train=9416, test=189, reason=train_too_small)
GRU fold 10/103 2023-09-05: fresh training (train=10361, test=189)
ListNet epoch 1/10: loss = 5.245539
ListNet epoch 2/10: loss = 5.250664
ListNet epoch 3/10: loss = 5.276170
ListNet epoch 4/10: loss = 5.214650
ListNet epoch 5/10: loss = 5.176077
ListNet epoch 6/10: loss = 5.081441
ListNet epoch 7/10: loss = 5.034048
ListNet epoch 8/10: loss = 4.954347
ListNet epoch 9/10: loss = 4.898819
ListNet epoch 10/10: loss = 4.994216
GRU fold 11/103 2023-09-12: fine-tune training (train=11306, test=189)
ListNet epoch 1/3: loss = 4.798376
ListNet epoch 2/3: loss = 4.867734
ListNet epoch 3/3: loss = 4.784018
GRU fold 12/103 2023-09-19: fine-tune training (train=12251, test=189)
ListNet epoch 1/3: loss = 4.730370
ListNet epoch 2/3: loss = 4.609157
ListNet epoch 3/3: loss = 4.564773
GRU fold 13/103 2023-09-26: fine-tune training (train=13196, test=189)
ListNet epoch 1/3: loss = 4.608408
ListNet epoch 2/3: loss = 4.687235
ListNet epoch 3/3: loss = 4.544692
GRU fold 14/103 2023-10-03: fine-tune training (train=14141, test=189)
ListNet epoch 1/3: loss = 4.809897
ListNet epoch 2/3: loss = 4.716619
ListNet epoch 3/3: loss = 4.462315
GRU fold 15/103 2023-10-10: fine-tune training (train=15086, test=190)
ListNet epoch 1/3: loss = 4.577369
ListNet epoch 2/3: loss = 4.647440
ListNet epoch 3/3: loss = 4.537217
GRU fold 16/103 2023-10-17: fine-tune training (train=16032, test=190)
ListNet epoch 1/3: loss = 4.669509
ListNet epoch 2/3: loss = 4.543435
ListNet epoch 3/3: loss = 4.844678
GRU fold 17/103 2023-10-24: fine-tune training (train=16982, test=190)
ListNet epoch 1/3: loss = 4.844973
ListNet epoch 2/3: loss = 4.699990
ListNet epoch 3/3: loss = 4.623871
GRU fold 18/103 2023-10-31: fine-tune training (train=17932, test=191)
ListNet epoch 1/3: loss = 4.630030
ListNet epoch 2/3: loss = 4.579385
ListNet epoch 3/3: loss = 4.681690
GRU fold 19/103 2023-11-07: fine-tune training (train=18885, test=191)
ListNet epoch 1/3: loss = 4.673519
ListNet epoch 2/3: loss = 4.563563
ListNet epoch 3/3: loss = 4.642594
GRU fold 20/103 2023-11-14: fine-tune training (train=19840, test=191)
ListNet epoch 1/3: loss = 4.577480
ListNet epoch 2/3: loss = 4.627142
ListNet epoch 3/3: loss = 4.589829
GRU fold 21/103 2023-11-21: fine-tune training (train=20795, test=191)
ListNet epoch 1/3: loss = 4.600983
ListNet epoch 2/3: loss = 4.636110
ListNet epoch 3/3: loss = 4.506185
GRU fold 22/103 2023-11-28: fine-tune training (train=21750, test=191)
ListNet epoch 1/3: loss = 4.603428
ListNet epoch 2/3: loss = 4.606476
ListNet epoch 3/3: loss = 4.431681
GRU fold 23/103 2023-12-05: fine-tune training (train=22705, test=191)
ListNet epoch 1/3: loss = 4.528183
ListNet epoch 2/3: loss = 4.458285
ListNet epoch 3/3: loss = 4.475206
GRU fold 24/103 2023-12-12: fine-tune training (train=23660, test=191)
ListNet epoch 1/3: loss = 4.376438
ListNet epoch 2/3: loss = 4.388027
ListNet epoch 3/3: loss = 4.337493
GRU fold 25/103 2023-12-19: fine-tune training (train=24615, test=191)
ListNet epoch 1/3: loss = 4.292145
ListNet epoch 2/3: loss = 4.488870
ListNet epoch 3/3: loss = 4.408891
GRU fold 26/103 2024-01-02: fine-tune training (train=25952, test=191)
ListNet epoch 1/3: loss = 4.337513
ListNet epoch 2/3: loss = 4.252117
ListNet epoch 3/3: loss = 4.443411
GRU fold 27/103 2024-01-09: fine-tune training (train=26907, test=191)
ListNet epoch 1/3: loss = 4.454466
ListNet epoch 2/3: loss = 4.370013
ListNet epoch 3/3: loss = 4.469317
GRU fold 28/103 2024-01-16: fine-tune training (train=27862, test=191)
ListNet epoch 1/3: loss = 4.415313
ListNet epoch 2/3: loss = 4.412108
ListNet epoch 3/3: loss = 4.441336
GRU fold 29/103 2024-01-23: fine-tune training (train=28817, test=191)
ListNet epoch 1/3: loss = 4.403641
ListNet epoch 2/3: loss = 4.475661
ListNet epoch 3/3: loss = 4.401011
GRU fold 30/103 2024-01-30: fine-tune training (train=29581, test=191)
ListNet epoch 1/3: loss = 4.405883
ListNet epoch 2/3: loss = 4.382632
ListNet epoch 3/3: loss = 4.359585
GRU fold 31/103 2024-02-06: fine-tune training (train=30536, test=191)
ListNet epoch 1/3: loss = 4.539563
ListNet epoch 2/3: loss = 4.384329
ListNet epoch 3/3: loss = 4.442951
GRU fold 32/103 2024-02-13: fine-tune training (train=31491, test=191)
ListNet epoch 1/3: loss = 4.423862
ListNet epoch 2/3: loss = 4.445033
ListNet epoch 3/3: loss = 4.410812
GRU fold 33/103 2024-02-20: fine-tune training (train=32446, test=191)
ListNet epoch 1/3: loss = 4.539728
ListNet epoch 2/3: loss = 4.548339
ListNet epoch 3/3: loss = 4.426226
GRU fold 34/103 2024-02-27: fine-tune training (train=33401, test=191)
ListNet epoch 1/3: loss = 4.432387
ListNet epoch 2/3: loss = 4.597525
ListNet epoch 3/3: loss = 4.444097
GRU fold 35/103 2024-03-05: fine-tune training (train=34356, test=191)
ListNet epoch 1/3: loss = 4.483866
ListNet epoch 2/3: loss = 4.436853
ListNet epoch 3/3: loss = 4.527692
GRU fold 36/103 2024-03-12: fresh training (train=35311, test=191)
ListNet epoch 1/10: loss = 5.255709
ListNet epoch 2/10: loss = 5.232568
ListNet epoch 3/10: loss = 5.076273
ListNet epoch 4/10: loss = 4.835296
ListNet epoch 5/10: loss = 4.696214
ListNet epoch 6/10: loss = 4.618593
ListNet epoch 7/10: loss = 4.680828
ListNet epoch 8/10: loss = 4.643667
ListNet epoch 9/10: loss = 4.433006
ListNet epoch 10/10: loss = 4.499775
GRU fold 37/103 2024-03-19: fine-tune training (train=36266, test=191)
ListNet epoch 1/3: loss = 4.470686
ListNet epoch 2/3: loss = 4.440780
ListNet epoch 3/3: loss = 4.575631
GRU fold 38/103 2024-03-26: fine-tune training (train=37221, test=191)
ListNet epoch 1/3: loss = 4.618885
ListNet epoch 2/3: loss = 4.607945
ListNet epoch 3/3: loss = 4.484796
GRU fold 39/103 2024-04-02: fine-tune training (train=37794, test=191)
ListNet epoch 1/3: loss = 4.477746
ListNet epoch 2/3: loss = 4.521429
ListNet epoch 3/3: loss = 4.450349
GRU fold 40/103 2024-04-09: fine-tune training (train=38749, test=192)
ListNet epoch 1/3: loss = 4.460584
ListNet epoch 2/3: loss = 4.405560
ListNet epoch 3/3: loss = 4.540757
GRU fold 41/103 2024-04-16: fine-tune training (train=39706, test=192)
ListNet epoch 1/3: loss = 4.493854
ListNet epoch 2/3: loss = 4.436860
ListNet epoch 3/3: loss = 4.490118
GRU fold 42/103 2024-04-23: fine-tune training (train=40666, test=192)
ListNet epoch 1/3: loss = 4.513581
ListNet epoch 2/3: loss = 4.346972
ListNet epoch 3/3: loss = 4.463531
GRU fold 43/103 2024-04-30: fine-tune training (train=41434, test=192)
ListNet epoch 1/3: loss = 4.397718
ListNet epoch 2/3: loss = 4.651151
ListNet epoch 3/3: loss = 4.519427
GRU fold 44/103 2024-05-07: fine-tune training (train=42394, test=192)
ListNet epoch 1/3: loss = 4.530834
ListNet epoch 2/3: loss = 4.470156
ListNet epoch 3/3: loss = 4.642861
GRU fold 45/103 2024-05-14: fine-tune training (train=43354, test=192)
ListNet epoch 1/3: loss = 4.304889
ListNet epoch 2/3: loss = 4.407197
ListNet epoch 3/3: loss = 4.466204
GRU fold 46/103 2024-05-21: fine-tune training (train=44314, test=192)
ListNet epoch 1/3: loss = 4.451005
ListNet epoch 2/3: loss = 4.510247
ListNet epoch 3/3: loss = 4.482171
GRU fold 47/103 2024-05-28: fine-tune training (train=45274, test=192)
ListNet epoch 1/3: loss = 4.573020
ListNet epoch 2/3: loss = 4.478208
ListNet epoch 3/3: loss = 4.466779
GRU fold 48/103 2024-06-04: fine-tune training (train=46234, test=192)
ListNet epoch 1/3: loss = 4.581151
ListNet epoch 2/3: loss = 4.591474
ListNet epoch 3/3: loss = 4.446883
GRU fold 49/103 2024-06-11: fine-tune training (train=47002, test=192)
ListNet epoch 1/3: loss = 4.407917
ListNet epoch 2/3: loss = 4.403373
ListNet epoch 3/3: loss = 4.470300
GRU fold 50/103 2024-06-18: fine-tune training (train=47962, test=192)
ListNet epoch 1/3: loss = 4.366867
ListNet epoch 2/3: loss = 4.483343
ListNet epoch 3/3: loss = 4.438744
GRU fold 51/103 2024-06-25: fine-tune training (train=48922, test=193)
ListNet epoch 1/3: loss = 4.542811
ListNet epoch 2/3: loss = 4.563703
ListNet epoch 3/3: loss = 4.533063
GRU fold 52/103 2024-07-02: fine-tune training (train=49886, test=193)
ListNet epoch 1/3: loss = 4.492303
ListNet epoch 2/3: loss = 4.456163
ListNet epoch 3/3: loss = 4.368953
GRU fold 53/103 2024-07-09: fine-tune training (train=50851, test=193)
ListNet epoch 1/3: loss = 4.384828
ListNet epoch 2/3: loss = 4.506498
ListNet epoch 3/3: loss = 4.471177
GRU fold 54/103 2024-07-16: fine-tune training (train=51816, test=193)
ListNet epoch 1/3: loss = 4.532706
ListNet epoch 2/3: loss = 4.475204
ListNet epoch 3/3: loss = 4.524010
GRU fold 55/103 2024-07-23: fine-tune training (train=52781, test=193)
ListNet epoch 1/3: loss = 4.595564
ListNet epoch 2/3: loss = 4.499977
ListNet epoch 3/3: loss = 4.516287
GRU fold 56/103 2024-07-30: fine-tune training (train=53746, test=194)
ListNet epoch 1/3: loss = 4.448308
ListNet epoch 2/3: loss = 4.473025
ListNet epoch 3/3: loss = 4.430231
GRU fold 57/103 2024-08-06: fine-tune training (train=54716, test=194)
ListNet epoch 1/3: loss = 4.491608
ListNet epoch 2/3: loss = 4.305842
ListNet epoch 3/3: loss = 4.388411
GRU fold 58/103 2024-08-13: fine-tune training (train=55686, test=194)
ListNet epoch 1/3: loss = 4.454208
ListNet epoch 2/3: loss = 4.349934
ListNet epoch 3/3: loss = 4.374199
GRU fold 59/103 2024-08-20: fine-tune training (train=56656, test=194)
ListNet epoch 1/3: loss = 4.337807
ListNet epoch 2/3: loss = 4.400833
ListNet epoch 3/3: loss = 4.364391
GRU fold 60/103 2024-08-27: fine-tune training (train=57626, test=194)
ListNet epoch 1/3: loss = 4.258749
ListNet epoch 2/3: loss = 4.289267
ListNet epoch 3/3: loss = 4.419641
GRU fold 61/103 2024-09-03: fine-tune training (train=58596, test=194)
ListNet epoch 1/3: loss = 4.362346
ListNet epoch 2/3: loss = 4.347200
ListNet epoch 3/3: loss = 4.414601
GRU fold 62/103 2024-09-10: fresh training (train=59566, test=194)
ListNet epoch 1/10: loss = 5.273274
ListNet epoch 2/10: loss = 5.222901
ListNet epoch 3/10: loss = 5.066637
ListNet epoch 4/10: loss = 5.091470
ListNet epoch 5/10: loss = 4.873569
ListNet epoch 6/10: loss = 4.767243
ListNet epoch 7/10: loss = 4.919704
ListNet epoch 8/10: loss = 4.691379
ListNet epoch 9/10: loss = 4.650184
ListNet epoch 10/10: loss = 4.795934
GRU fold 63/103 2024-09-17: fine-tune training (train=60536, test=194)
ListNet epoch 1/3: loss = 4.593107
ListNet epoch 2/3: loss = 4.575972
ListNet epoch 3/3: loss = 4.522171
GRU fold 64/103 2024-09-24: fine-tune training (train=61506, test=194)
ListNet epoch 1/3: loss = 4.487104
ListNet epoch 2/3: loss = 4.543865
ListNet epoch 3/3: loss = 4.540726
GRU fold 65/103 2024-10-01: fine-tune training (train=62476, test=194)
ListNet epoch 1/3: loss = 4.614161
ListNet epoch 2/3: loss = 4.634163
ListNet epoch 3/3: loss = 4.462292
GRU fold 66/103 2024-10-08: fine-tune training (train=63446, test=194)
ListNet epoch 1/3: loss = 4.513751
ListNet epoch 2/3: loss = 4.529455
ListNet epoch 3/3: loss = 4.564306
GRU fold 67/103 2024-10-15: fine-tune training (train=64416, test=194)
ListNet epoch 1/3: loss = 4.501664
ListNet epoch 2/3: loss = 4.591898
ListNet epoch 3/3: loss = 4.568536
GRU fold 68/103 2024-10-22: fine-tune training (train=65386, test=194)
ListNet epoch 1/3: loss = 4.505390
ListNet epoch 2/3: loss = 4.540900
ListNet epoch 3/3: loss = 4.673153
GRU fold 69/103 2024-10-29: fine-tune training (train=66356, test=194)
ListNet epoch 1/3: loss = 4.489393
ListNet epoch 2/3: loss = 4.756503
ListNet epoch 3/3: loss = 4.600409
GRU fold 70/103 2024-11-05: fine-tune training (train=67326, test=194)
ListNet epoch 1/3: loss = 4.534259
ListNet epoch 2/3: loss = 4.533640
ListNet epoch 3/3: loss = 4.720496
GRU fold 71/103 2024-11-12: fine-tune training (train=68296, test=194)
ListNet epoch 1/3: loss = 4.519139
ListNet epoch 2/3: loss = 4.582093
ListNet epoch 3/3: loss = 4.591725
GRU fold 72/103 2024-11-19: fine-tune training (train=69266, test=194)
ListNet epoch 1/3: loss = 4.678020
ListNet epoch 2/3: loss = 4.776798
ListNet epoch 3/3: loss = 4.672861
GRU fold 73/103 2024-11-26: fine-tune training (train=70236, test=194)
ListNet epoch 1/3: loss = 4.878292
ListNet epoch 2/3: loss = 4.560543
ListNet epoch 3/3: loss = 4.585087
GRU fold 74/103 2024-12-03: fine-tune training (train=71206, test=194)
ListNet epoch 1/3: loss = 4.645576
ListNet epoch 2/3: loss = 4.866109
ListNet epoch 3/3: loss = 4.743891
GRU fold 75/103 2024-12-10: fine-tune training (train=72176, test=194)
ListNet epoch 1/3: loss = 4.676851
ListNet epoch 2/3: loss = 4.793052
ListNet epoch 3/3: loss = 4.743568
GRU fold 76/103 2024-12-17: fine-tune training (train=73146, test=194)
ListNet epoch 1/3: loss = 4.708575
ListNet epoch 2/3: loss = 4.741663
ListNet epoch 3/3: loss = 4.827124
GRU fold 77/103 2024-12-24: fine-tune training (train=74116, test=194)
ListNet epoch 1/3: loss = 4.703960
ListNet epoch 2/3: loss = 4.744722
ListNet epoch 3/3: loss = 4.688238
GRU fold 78/103 2024-12-31: fine-tune training (train=74698, test=194)
ListNet epoch 1/3: loss = 4.615490
ListNet epoch 2/3: loss = 4.669470
ListNet epoch 3/3: loss = 4.724373
GRU fold 79/103 2025-01-07: fine-tune training (train=75474, test=194)
ListNet epoch 1/3: loss = 4.614078
ListNet epoch 2/3: loss = 4.792381
ListNet epoch 3/3: loss = 4.625935
GRU fold 80/103 2025-01-14: fine-tune training (train=76444, test=194)
ListNet epoch 1/3: loss = 4.664217
ListNet epoch 2/3: loss = 4.593077
ListNet epoch 3/3: loss = 4.692654
GRU fold 81/103 2025-01-21: fine-tune training (train=77414, test=195)
ListNet epoch 1/3: loss = 4.751091
ListNet epoch 2/3: loss = 4.653390
ListNet epoch 3/3: loss = 4.654057
GRU fold 82/103 2025-01-28: fine-tune training (train=78192, test=195)
ListNet epoch 1/3: loss = 4.716058
ListNet epoch 2/3: loss = 4.660687
ListNet epoch 3/3: loss = 4.751438
GRU fold 83/103 2025-02-04: fine-tune training (train=79167, test=195)
ListNet epoch 1/3: loss = 4.721706
ListNet epoch 2/3: loss = 4.668377
ListNet epoch 3/3: loss = 4.653962
GRU fold 84/103 2025-02-11: fine-tune training (train=80142, test=195)
ListNet epoch 1/3: loss = 4.616298
ListNet epoch 2/3: loss = 4.577961
ListNet epoch 3/3: loss = 4.561627
GRU fold 85/103 2025-02-18: fine-tune training (train=81117, test=195)
ListNet epoch 1/3: loss = 4.694065
ListNet epoch 2/3: loss = 4.675854
ListNet epoch 3/3: loss = 4.706732
GRU fold 86/103 2025-02-25: fine-tune training (train=82092, test=195)
ListNet epoch 1/3: loss = 4.622117
ListNet epoch 2/3: loss = 4.652847
ListNet epoch 3/3: loss = 4.600435
GRU fold 87/103 2025-03-04: fine-tune training (train=83067, test=195)
ListNet epoch 1/3: loss = 4.590865
ListNet epoch 2/3: loss = 4.625018
ListNet epoch 3/3: loss = 4.688823
GRU fold 88/103 2025-03-11: fresh training (train=84042, test=195)
ListNet epoch 1/10: loss = 5.272611
ListNet epoch 2/10: loss = 5.289113
ListNet epoch 3/10: loss = 5.274585
ListNet epoch 4/10: loss = 5.266223
ListNet epoch 5/10: loss = 5.250919
ListNet epoch 6/10: loss = 5.283904
ListNet epoch 7/10: loss = 5.276137
ListNet epoch 8/10: loss = 5.250286
ListNet epoch 9/10: loss = 5.210984
ListNet epoch 10/10: loss = 5.110080
GRU fold 89/103 2025-03-18: fine-tune training (train=85017, test=195)
ListNet epoch 1/3: loss = 5.076394
ListNet epoch 2/3: loss = 5.077341
ListNet epoch 3/3: loss = 5.032237
GRU fold 90/103 2025-03-25: fine-tune training (train=85992, test=195)
ListNet epoch 1/3: loss = 5.033682
ListNet epoch 2/3: loss = 4.979906
ListNet epoch 3/3: loss = 4.989498
GRU fold 91/103 2025-04-01: fine-tune training (train=86967, test=195)
ListNet epoch 1/3: loss = 4.898257
ListNet epoch 2/3: loss = 4.934364
ListNet epoch 3/3: loss = 4.876993
GRU fold 92/103 2025-04-08: fine-tune training (train=87942, test=195)
ListNet epoch 1/3: loss = 4.918805
ListNet epoch 2/3: loss = 4.851220
ListNet epoch 3/3: loss = 4.924828
GRU fold 93/103 2025-04-15: fine-tune training (train=88917, test=195)
ListNet epoch 1/3: loss = 4.881989
ListNet epoch 2/3: loss = 4.843125
ListNet epoch 3/3: loss = 4.830199
GRU fold 94/103 2025-04-22: fine-tune training (train=89502, test=195)
ListNet epoch 1/3: loss = 4.852686
ListNet epoch 2/3: loss = 4.829717
ListNet epoch 3/3: loss = 4.915770
GRU fold 95/103 2025-04-29: fine-tune training (train=90282, test=195)
ListNet epoch 1/3: loss = 4.820713
ListNet epoch 2/3: loss = 4.850453
ListNet epoch 3/3: loss = 4.879658
GRU fold 96/103 2025-05-06: fine-tune training (train=91257, test=195)
ListNet epoch 1/3: loss = 4.896988
ListNet epoch 2/3: loss = 4.858361
ListNet epoch 3/3: loss = 4.858463
GRU fold 97/103 2025-05-13: fine-tune training (train=92232, test=195)
ListNet epoch 1/3: loss = 4.878353
ListNet epoch 2/3: loss = 4.846957
ListNet epoch 3/3: loss = 4.806625
GRU fold 98/103 2025-05-20: fine-tune training (train=93207, test=195)
ListNet epoch 1/3: loss = 4.838426
ListNet epoch 2/3: loss = 4.768079
ListNet epoch 3/3: loss = 4.770047
GRU fold 99/103 2025-05-27: fine-tune training (train=94182, test=195)
ListNet epoch 1/3: loss = 4.974044
ListNet epoch 2/3: loss = 4.982878
ListNet epoch 3/3: loss = 4.857688
GRU fold 100/103 2025-06-03: fine-tune training (train=95157, test=195)
ListNet epoch 1/3: loss = 4.906680
ListNet epoch 2/3: loss = 4.850679
ListNet epoch 3/3: loss = 4.856930
GRU fold 101/103 2025-06-10: fine-tune training (train=95937, test=195)
ListNet epoch 1/3: loss = 4.790576
ListNet epoch 2/3: loss = 4.843250
ListNet epoch 3/3: loss = 4.917756
GRU fold 102/103 2025-06-17: fine-tune training (train=96912, test=195)
ListNet epoch 1/3: loss = 4.907955
ListNet epoch 2/3: loss = 4.964006
ListNet epoch 3/3: loss = 4.843753
GRU fold 103/103 2025-06-24: fine-tune training (train=97887, test=197)
ListNet epoch 1/3: loss = 4.978097
ListNet epoch 2/3: loss = 4.964668
ListNet epoch 3/3: loss = 4.957417

/mnt/c/Users/Gordon Li/Desktop/systematic_project/scripts/models/gru/tune_gru.py:88: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  daily_ic = preds.groupby("Date").apply(

2/6: IC = 0.01731 (raw_ic=0.01731, trained_folds=94, skipped_folds=9, coverage=91.3%)
GRU fold 1/103 2023-07-04: skipped (train=1880, test=188, reason=train_too_small)
GRU fold 2/103 2023-07-11: skipped (train=2820, test=188, reason=train_too_small)
GRU fold 3/103 2023-07-18: skipped (train=3760, test=188, reason=train_too_small)
GRU fold 4/103 2023-07-25: skipped (train=4700, test=188, reason=train_too_small)
GRU fold 5/103 2023-08-01: skipped (train=5640, test=189, reason=train_too_small)
GRU fold 6/103 2023-08-08: skipped (train=6581, test=189, reason=train_too_small)
GRU fold 7/103 2023-08-15: skipped (train=7526, test=189, reason=train_too_small)
GRU fold 8/103 2023-08-22: skipped (train=8471, test=189, reason=train_too_small)
GRU fold 9/103 2023-08-29: skipped (train=9416, test=189, reason=train_too_small)
GRU fold 10/103 2023-09-05: fresh training (train=10361, test=189)
ListNet epoch 1/10: loss = 5.249177
ListNet epoch 2/10: loss = 5.266210
ListNet epoch 3/10: loss = 5.290120
ListNet epoch 4/10: loss = 5.257349
Early stopping at epoch 4/10
GRU fold 11/103 2023-09-12: fine-tune training (train=11306, test=189)
ListNet epoch 1/1: loss = 5.281805
GRU fold 12/103 2023-09-19: fine-tune training (train=12251, test=189)
ListNet epoch 1/1: loss = 5.239338
GRU fold 13/103 2023-09-26: fine-tune training (train=13196, test=189)
ListNet epoch 1/1: loss = 5.231518
GRU fold 14/103 2023-10-03: fine-tune training (train=14141, test=189)
ListNet epoch 1/1: loss = 5.267543
GRU fold 15/103 2023-10-10: fine-tune training (train=15086, test=190)
ListNet epoch 1/1: loss = 5.231045
GRU fold 16/103 2023-10-17: fine-tune training (train=16032, test=190)
ListNet epoch 1/1: loss = 5.220040
GRU fold 17/103 2023-10-24: fine-tune training (train=16982, test=190)
ListNet epoch 1/1: loss = 5.221770
GRU fold 18/103 2023-10-31: fine-tune training (train=17932, test=191)
ListNet epoch 1/1: loss = 5.234429
GRU fold 19/103 2023-11-07: fine-tune training (train=18885, test=191)
ListNet epoch 1/1: loss = 5.201317
GRU fold 20/103 2023-11-14: fine-tune training (train=19840, test=191)
ListNet epoch 1/1: loss = 5.201657
GRU fold 21/103 2023-11-21: fine-tune training (train=20795, test=191)
ListNet epoch 1/1: loss = 5.157522
GRU fold 22/103 2023-11-28: fine-tune training (train=21750, test=191)
ListNet epoch 1/1: loss = 5.144612
GRU fold 23/103 2023-12-05: fine-tune training (train=22705, test=191)
ListNet epoch 1/1: loss = 5.141567
GRU fold 24/103 2023-12-12: fine-tune training (train=23660, test=191)
ListNet epoch 1/1: loss = 5.085206
GRU fold 25/103 2023-12-19: fine-tune training (train=24615, test=191)
ListNet epoch 1/1: loss = 5.077576
GRU fold 26/103 2024-01-02: fine-tune training (train=25952, test=191)
ListNet epoch 1/1: loss = 5.052391
GRU fold 27/103 2024-01-09: fine-tune training (train=26907, test=191)
ListNet epoch 1/1: loss = 5.027192
GRU fold 28/103 2024-01-16: fine-tune training (train=27862, test=191)
ListNet epoch 1/1: loss = 4.964387
GRU fold 29/103 2024-01-23: fine-tune training (train=28817, test=191)
ListNet epoch 1/1: loss = 4.932105
GRU fold 30/103 2024-01-30: fine-tune training (train=29581, test=191)
ListNet epoch 1/1: loss = 4.886100
GRU fold 31/103 2024-02-06: fine-tune training (train=30536, test=191)
ListNet epoch 1/1: loss = 4.836446
GRU fold 32/103 2024-02-13: fine-tune training (train=31491, test=191)
ListNet epoch 1/1: loss = 4.799470
GRU fold 33/103 2024-02-20: fine-tune training (train=32446, test=191)
ListNet epoch 1/1: loss = 4.745249
GRU fold 34/103 2024-02-27: fine-tune training (train=33401, test=191)
ListNet epoch 1/1: loss = 4.760314
GRU fold 35/103 2024-03-05: fine-tune training (train=34356, test=191)
ListNet epoch 1/1: loss = 4.707235
GRU fold 36/103 2024-03-12: fresh training (train=35311, test=191)
ListNet epoch 1/10: loss = 5.266539
ListNet epoch 2/10: loss = 5.260773
ListNet epoch 3/10: loss = 5.238833
ListNet epoch 4/10: loss = 5.183482
ListNet epoch 5/10: loss = 5.170096
ListNet epoch 6/10: loss = 5.100711
ListNet epoch 7/10: loss = 5.031352
ListNet epoch 8/10: loss = 4.974781
ListNet epoch 9/10: loss = 4.890771
ListNet epoch 10/10: loss = 4.826529
GRU fold 37/103 2024-03-19: fine-tune training (train=36266, test=191)
ListNet epoch 1/1: loss = 4.764273
GRU fold 38/103 2024-03-26: fine-tune training (train=37221, test=191)
ListNet epoch 1/1: loss = 4.728434
GRU fold 39/103 2024-04-02: fine-tune training (train=37794, test=191)
ListNet epoch 1/1: loss = 4.676435
GRU fold 40/103 2024-04-09: fine-tune training (train=38749, test=192)
ListNet epoch 1/1: loss = 4.658835
GRU fold 41/103 2024-04-16: fine-tune training (train=39706, test=192)
ListNet epoch 1/1: loss = 4.592574
GRU fold 42/103 2024-04-23: fine-tune training (train=40666, test=192)
ListNet epoch 1/1: loss = 4.587808
GRU fold 43/103 2024-04-30: fine-tune training (train=41434, test=192)
ListNet epoch 1/1: loss = 4.565766
GRU fold 44/103 2024-05-07: fine-tune training (train=42394, test=192)
ListNet epoch 1/1: loss = 4.521144
GRU fold 45/103 2024-05-14: fine-tune training (train=43354, test=192)
ListNet epoch 1/1: loss = 4.540188
GRU fold 46/103 2024-05-21: fine-tune training (train=44314, test=192)
ListNet epoch 1/1: loss = 4.486398
GRU fold 47/103 2024-05-28: fine-tune training (train=45274, test=192)
ListNet epoch 1/1: loss = 4.554550
GRU fold 48/103 2024-06-04: fine-tune training (train=46234, test=192)
ListNet epoch 1/1: loss = 4.520230
GRU fold 49/103 2024-06-11: fine-tune training (train=47002, test=192)
ListNet epoch 1/1: loss = 4.499559
GRU fold 50/103 2024-06-18: fine-tune training (train=47962, test=192)
ListNet epoch 1/1: loss = 4.484514
GRU fold 51/103 2024-06-25: fine-tune training (train=48922, test=193)
ListNet epoch 1/1: loss = 4.453748
GRU fold 52/103 2024-07-02: fine-tune training (train=49886, test=193)
ListNet epoch 1/1: loss = 4.420344
GRU fold 53/103 2024-07-09: fine-tune training (train=50851, test=193)
ListNet epoch 1/1: loss = 4.403962
GRU fold 54/103 2024-07-16: fine-tune training (train=51816, test=193)
ListNet epoch 1/1: loss = 4.458613
GRU fold 55/103 2024-07-23: fine-tune training (train=52781, test=193)
ListNet epoch 1/1: loss = 4.436321
GRU fold 56/103 2024-07-30: fine-tune training (train=53746, test=194)
ListNet epoch 1/1: loss = 4.457743
GRU fold 57/103 2024-08-06: fine-tune training (train=54716, test=194)
ListNet epoch 1/1: loss = 4.450268
GRU fold 58/103 2024-08-13: fine-tune training (train=55686, test=194)
ListNet epoch 1/1: loss = 4.478850
GRU fold 59/103 2024-08-20: fine-tune training (train=56656, test=194)
ListNet epoch 1/1: loss = 4.321359
GRU fold 60/103 2024-08-27: fine-tune training (train=57626, test=194)
ListNet epoch 1/1: loss = 4.375672
GRU fold 61/103 2024-09-03: fine-tune training (train=58596, test=194)
ListNet epoch 1/1: loss = 4.370610
GRU fold 62/103 2024-09-10: fresh training (train=59566, test=194)
ListNet epoch 1/10: loss = 5.278787
ListNet epoch 2/10: loss = 5.275918
ListNet epoch 3/10: loss = 5.262575
ListNet epoch 4/10: loss = 5.231944
ListNet epoch 5/10: loss = 5.167852
ListNet epoch 6/10: loss = 5.068592
ListNet epoch 7/10: loss = 4.956547
ListNet epoch 8/10: loss = 4.849926
ListNet epoch 9/10: loss = 4.768837
ListNet epoch 10/10: loss = 4.687672
GRU fold 63/103 2024-09-17: fine-tune training (train=60536, test=194)
ListNet epoch 1/1: loss = 4.644915
GRU fold 64/103 2024-09-24: fine-tune training (train=61506, test=194)
ListNet epoch 1/1: loss = 4.626675
GRU fold 65/103 2024-10-01: fine-tune training (train=62476, test=194)
ListNet epoch 1/1: loss = 4.598009
GRU fold 66/103 2024-10-08: fine-tune training (train=63446, test=194)
ListNet epoch 1/1: loss = 4.582258
GRU fold 67/103 2024-10-15: fine-tune training (train=64416, test=194)
ListNet epoch 1/1: loss = 4.584787
GRU fold 68/103 2024-10-22: fine-tune training (train=65386, test=194)
ListNet epoch 1/1: loss = 4.569616
GRU fold 69/103 2024-10-29: fine-tune training (train=66356, test=194)
ListNet epoch 1/1: loss = 4.586900
GRU fold 70/103 2024-11-05: fine-tune training (train=67326, test=194)
ListNet epoch 1/1: loss = 4.638962
GRU fold 71/103 2024-11-12: fine-tune training (train=68296, test=194)
ListNet epoch 1/1: loss = 4.616168
GRU fold 72/103 2024-11-19: fine-tune training (train=69266, test=194)
ListNet epoch 1/1: loss = 4.628512
GRU fold 73/103 2024-11-26: fine-tune training (train=70236, test=194)
ListNet epoch 1/1: loss = 4.583022
GRU fold 74/103 2024-12-03: fine-tune training (train=71206, test=194)
ListNet epoch 1/1: loss = 4.607917
GRU fold 75/103 2024-12-10: fine-tune training (train=72176, test=194)
ListNet epoch 1/1: loss = 4.612710
GRU fold 76/103 2024-12-17: fine-tune training (train=73146, test=194)
ListNet epoch 1/1: loss = 4.635231
GRU fold 77/103 2024-12-24: fine-tune training (train=74116, test=194)
ListNet epoch 1/1: loss = 4.593369
GRU fold 78/103 2024-12-31: fine-tune training (train=74698, test=194)
ListNet epoch 1/1: loss = 4.623061
GRU fold 79/103 2025-01-07: fine-tune training (train=75474, test=194)
ListNet epoch 1/1: loss = 4.586081
GRU fold 80/103 2025-01-14: fine-tune training (train=76444, test=194)
ListNet epoch 1/1: loss = 4.540934
GRU fold 81/103 2025-01-21: fine-tune training (train=77414, test=195)
ListNet epoch 1/1: loss = 4.589938
GRU fold 82/103 2025-01-28: fine-tune training (train=78192, test=195)
ListNet epoch 1/1: loss = 4.601533
GRU fold 83/103 2025-02-04: fine-tune training (train=79167, test=195)
ListNet epoch 1/1: loss = 4.646773
GRU fold 84/103 2025-02-11: fine-tune training (train=80142, test=195)
ListNet epoch 1/1: loss = 4.541431
GRU fold 85/103 2025-02-18: fine-tune training (train=81117, test=195)
ListNet epoch 1/1: loss = 4.533354
GRU fold 86/103 2025-02-25: fine-tune training (train=82092, test=195)
ListNet epoch 1/1: loss = 4.475604
GRU fold 87/103 2025-03-04: fine-tune training (train=83067, test=195)
ListNet epoch 1/1: loss = 4.530409
GRU fold 88/103 2025-03-11: fresh training (train=84042, test=195)
ListNet epoch 1/10: loss = 5.273014
ListNet epoch 2/10: loss = 5.295300
ListNet epoch 3/10: loss = 5.280743
ListNet epoch 4/10: loss = 5.257104
ListNet epoch 5/10: loss = 5.270219
ListNet epoch 6/10: loss = 5.268248
ListNet epoch 7/10: loss = 5.212983
ListNet epoch 8/10: loss = 5.203634
ListNet epoch 9/10: loss = 5.131704
ListNet epoch 10/10: loss = 5.108893
GRU fold 89/103 2025-03-18: fine-tune training (train=85017, test=195)
ListNet epoch 1/1: loss = 5.043433
GRU fold 90/103 2025-03-25: fine-tune training (train=85992, test=195)
ListNet epoch 1/1: loss = 5.039834
GRU fold 91/103 2025-04-01: fine-tune training (train=86967, test=195)
ListNet epoch 1/1: loss = 5.004715
GRU fold 92/103 2025-04-08: fine-tune training (train=87942, test=195)
ListNet epoch 1/1: loss = 4.975899
GRU fold 93/103 2025-04-15: fine-tune training (train=88917, test=195)
ListNet epoch 1/1: loss = 4.974443
GRU fold 94/103 2025-04-22: fine-tune training (train=89502, test=195)
ListNet epoch 1/1: loss = 4.962013
GRU fold 95/103 2025-04-29: fine-tune training (train=90282, test=195)
ListNet epoch 1/1: loss = 4.942553
GRU fold 96/103 2025-05-06: fine-tune training (train=91257, test=195)
ListNet epoch 1/1: loss = 4.932198
GRU fold 97/103 2025-05-13: fine-tune training (train=92232, test=195)
ListNet epoch 1/1: loss = 4.914882
GRU fold 98/103 2025-05-20: fine-tune training (train=93207, test=195)
ListNet epoch 1/1: loss = 4.915213
GRU fold 99/103 2025-05-27: fine-tune training (train=94182, test=195)
ListNet epoch 1/1: loss = 4.858676
GRU fold 100/103 2025-06-03: fine-tune training (train=95157, test=195)
ListNet epoch 1/1: loss = 4.858841
GRU fold 101/103 2025-06-10: fine-tune training (train=95937, test=195)
ListNet epoch 1/1: loss = 4.841439
GRU fold 102/103 2025-06-17: fine-tune training (train=96912, test=195)
ListNet epoch 1/1: loss = 4.842281
GRU fold 103/103 2025-06-24: fine-tune training (train=97887, test=197)
ListNet epoch 1/1: loss = 4.821289

/mnt/c/Users/Gordon Li/Desktop/systematic_project/scripts/models/gru/tune_gru.py:88: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  daily_ic = preds.groupby("Date").apply(

3/6: IC = 0.01517 (raw_ic=0.01517, trained_folds=94, skipped_folds=9, coverage=91.3%)
GRU fold 1/103 2023-07-04: skipped (train=1880, test=188, reason=train_too_small)
GRU fold 2/103 2023-07-11: skipped (train=2820, test=188, reason=train_too_small)
GRU fold 3/103 2023-07-18: skipped (train=3760, test=188, reason=train_too_small)
GRU fold 4/103 2023-07-25: skipped (train=4700, test=188, reason=train_too_small)
GRU fold 5/103 2023-08-01: skipped (train=5640, test=189, reason=train_too_small)
GRU fold 6/103 2023-08-08: skipped (train=6581, test=189, reason=train_too_small)
GRU fold 7/103 2023-08-15: skipped (train=7526, test=189, reason=train_too_small)
GRU fold 8/103 2023-08-22: skipped (train=8471, test=189, reason=train_too_small)
GRU fold 9/103 2023-08-29: skipped (train=9416, test=189, reason=train_too_small)
GRU fold 10/103 2023-09-05: fresh training (train=10361, test=189)
ListNet epoch 1/10: loss = 5.295005
ListNet epoch 2/10: loss = 5.250290
ListNet epoch 3/10: loss = 5.230853
ListNet epoch 4/10: loss = 5.181010
ListNet epoch 5/10: loss = 5.198905
ListNet epoch 6/10: loss = 5.160371
ListNet epoch 7/10: loss = 5.120634
ListNet epoch 8/10: loss = 5.074743
ListNet epoch 9/10: loss = 5.017158
ListNet epoch 10/10: loss = 4.923443
GRU fold 11/103 2023-09-12: fine-tune training (train=11306, test=189)
ListNet epoch 1/2: loss = 4.863797
ListNet epoch 2/2: loss = 4.841750
GRU fold 12/103 2023-09-19: fine-tune training (train=12251, test=189)
ListNet epoch 1/2: loss = 4.718005
ListNet epoch 2/2: loss = 4.756176
GRU fold 13/103 2023-09-26: fine-tune training (train=13196, test=189)
ListNet epoch 1/2: loss = 4.652082
ListNet epoch 2/2: loss = 4.751796
GRU fold 14/103 2023-10-03: fine-tune training (train=14141, test=189)
ListNet epoch 1/2: loss = 4.671622
ListNet epoch 2/2: loss = 4.645446
GRU fold 15/103 2023-10-10: fine-tune training (train=15086, test=190)
ListNet epoch 1/2: loss = 4.660964
ListNet epoch 2/2: loss = 4.698870
GRU fold 16/103 2023-10-17: fine-tune training (train=16032, test=190)
ListNet epoch 1/2: loss = 4.695968
ListNet epoch 2/2: loss = 4.694527
GRU fold 17/103 2023-10-24: fine-tune training (train=16982, test=190)
ListNet epoch 1/2: loss = 4.621500
ListNet epoch 2/2: loss = 4.557976
GRU fold 18/103 2023-10-31: fine-tune training (train=17932, test=191)
ListNet epoch 1/2: loss = 4.527718
ListNet epoch 2/2: loss = 4.592772
GRU fold 19/103 2023-11-07: fine-tune training (train=18885, test=191)
ListNet epoch 1/2: loss = 4.599452
ListNet epoch 2/2: loss = 4.509101
GRU fold 20/103 2023-11-14: fine-tune training (train=19840, test=191)
ListNet epoch 1/2: loss = 4.489720
ListNet epoch 2/2: loss = 4.451228
GRU fold 21/103 2023-11-21: fine-tune training (train=20795, test=191)
ListNet epoch 1/2: loss = 4.516674
ListNet epoch 2/2: loss = 4.498165
GRU fold 22/103 2023-11-28: fine-tune training (train=21750, test=191)
ListNet epoch 1/2: loss = 4.486254
ListNet epoch 2/2: loss = 4.411766
GRU fold 23/103 2023-12-05: fine-tune training (train=22705, test=191)
ListNet epoch 1/2: loss = 4.405669
ListNet epoch 2/2: loss = 4.336662
GRU fold 24/103 2023-12-12: fine-tune training (train=23660, test=191)
ListNet epoch 1/2: loss = 4.398142
ListNet epoch 2/2: loss = 4.407831
GRU fold 25/103 2023-12-19: fine-tune training (train=24615, test=191)
ListNet epoch 1/2: loss = 4.406080
ListNet epoch 2/2: loss = 4.362407
GRU fold 26/103 2024-01-02: fine-tune training (train=25952, test=191)
ListNet epoch 1/2: loss = 4.325565
ListNet epoch 2/2: loss = 4.334846
GRU fold 27/103 2024-01-09: fine-tune training (train=26907, test=191)
ListNet epoch 1/2: loss = 4.402158
ListNet epoch 2/2: loss = 4.428366
GRU fold 28/103 2024-01-16: fine-tune training (train=27862, test=191)
ListNet epoch 1/2: loss = 4.347871
ListNet epoch 2/2: loss = 4.403225
GRU fold 29/103 2024-01-23: fine-tune training (train=28817, test=191)
ListNet epoch 1/2: loss = 4.375013
ListNet epoch 2/2: loss = 4.337815
GRU fold 30/103 2024-01-30: fine-tune training (train=29581, test=191)
ListNet epoch 1/2: loss = 4.385127
ListNet epoch 2/2: loss = 4.464766
GRU fold 31/103 2024-02-06: fine-tune training (train=30536, test=191)
ListNet epoch 1/2: loss = 4.367339
ListNet epoch 2/2: loss = 4.379665
GRU fold 32/103 2024-02-13: fine-tune training (train=31491, test=191)
ListNet epoch 1/2: loss = 4.357107
ListNet epoch 2/2: loss = 4.313500
GRU fold 33/103 2024-02-20: fine-tune training (train=32446, test=191)
ListNet epoch 1/2: loss = 4.306827
ListNet epoch 2/2: loss = 4.338150
GRU fold 34/103 2024-02-27: fine-tune training (train=33401, test=191)
ListNet epoch 1/2: loss = 4.334243
ListNet epoch 2/2: loss = 4.350393
GRU fold 35/103 2024-03-05: fine-tune training (train=34356, test=191)
ListNet epoch 1/2: loss = 4.416028
ListNet epoch 2/2: loss = 4.409042
GRU fold 36/103 2024-03-12: fresh training (train=35311, test=191)
ListNet epoch 1/10: loss = 5.294985
ListNet epoch 2/10: loss = 5.254383
ListNet epoch 3/10: loss = 5.095124
ListNet epoch 4/10: loss = 4.840218
ListNet epoch 5/10: loss = 4.702475
ListNet epoch 6/10: loss = 4.571284
ListNet epoch 7/10: loss = 4.579294
ListNet epoch 8/10: loss = 4.582080
ListNet epoch 9/10: loss = 4.556064
ListNet epoch 10/10: loss = 4.457352
GRU fold 37/103 2024-03-19: fine-tune training (train=36266, test=191)
ListNet epoch 1/2: loss = 4.489236
ListNet epoch 2/2: loss = 4.440353
GRU fold 38/103 2024-03-26: fine-tune training (train=37221, test=191)
ListNet epoch 1/2: loss = 4.425987
ListNet epoch 2/2: loss = 4.330182
GRU fold 39/103 2024-04-02: fine-tune training (train=37794, test=191)
ListNet epoch 1/2: loss = 4.386703
ListNet epoch 2/2: loss = 4.389598
GRU fold 40/103 2024-04-09: fine-tune training (train=38749, test=192)
ListNet epoch 1/2: loss = 4.376422
ListNet epoch 2/2: loss = 4.380358
GRU fold 41/103 2024-04-16: fine-tune training (train=39706, test=192)
ListNet epoch 1/2: loss = 4.406372
ListNet epoch 2/2: loss = 4.556408
GRU fold 42/103 2024-04-23: fine-tune training (train=40666, test=192)
ListNet epoch 1/2: loss = 4.337636
ListNet epoch 2/2: loss = 4.345266
GRU fold 43/103 2024-04-30: fine-tune training (train=41434, test=192)
ListNet epoch 1/2: loss = 4.245465
ListNet epoch 2/2: loss = 4.315884
GRU fold 44/103 2024-05-07: fine-tune training (train=42394, test=192)
ListNet epoch 1/2: loss = 4.378708
ListNet epoch 2/2: loss = 4.416224
GRU fold 45/103 2024-05-14: fine-tune training (train=43354, test=192)
ListNet epoch 1/2: loss = 4.375442
ListNet epoch 2/2: loss = 4.393051
GRU fold 46/103 2024-05-21: fine-tune training (train=44314, test=192)
ListNet epoch 1/2: loss = 4.349891
ListNet epoch 2/2: loss = 4.536401
GRU fold 47/103 2024-05-28: fine-tune training (train=45274, test=192)
ListNet epoch 1/2: loss = 4.427987
ListNet epoch 2/2: loss = 4.447271
GRU fold 48/103 2024-06-04: fine-tune training (train=46234, test=192)
ListNet epoch 1/2: loss = 4.377524
ListNet epoch 2/2: loss = 4.364577
GRU fold 49/103 2024-06-11: fine-tune training (train=47002, test=192)
ListNet epoch 1/2: loss = 4.368896
ListNet epoch 2/2: loss = 4.318730
GRU fold 50/103 2024-06-18: fine-tune training (train=47962, test=192)
ListNet epoch 1/2: loss = 4.388008
ListNet epoch 2/2: loss = 4.436209
GRU fold 51/103 2024-06-25: fine-tune training (train=48922, test=193)
ListNet epoch 1/2: loss = 4.457555
ListNet epoch 2/2: loss = 4.311810
GRU fold 52/103 2024-07-02: fine-tune training (train=49886, test=193)
ListNet epoch 1/2: loss = 4.349328
ListNet epoch 2/2: loss = 4.297503
GRU fold 53/103 2024-07-09: fine-tune training (train=50851, test=193)
ListNet epoch 1/2: loss = 4.311884
ListNet epoch 2/2: loss = 4.334775
GRU fold 54/103 2024-07-16: fine-tune training (train=51816, test=193)
ListNet epoch 1/2: loss = 4.362051
ListNet epoch 2/2: loss = 4.345306
GRU fold 55/103 2024-07-23: fine-tune training (train=52781, test=193)
ListNet epoch 1/2: loss = 4.340873
ListNet epoch 2/2: loss = 4.295436
GRU fold 56/103 2024-07-30: fine-tune training (train=53746, test=194)
ListNet epoch 1/2: loss = 4.254608
ListNet epoch 2/2: loss = 4.314558
GRU fold 57/103 2024-08-06: fine-tune training (train=54716, test=194)
ListNet epoch 1/2: loss = 4.334870
ListNet epoch 2/2: loss = 4.282945
GRU fold 58/103 2024-08-13: fine-tune training (train=55686, test=194)
ListNet epoch 1/2: loss = 4.343911
ListNet epoch 2/2: loss = 4.348140
GRU fold 59/103 2024-08-20: fine-tune training (train=56656, test=194)
ListNet epoch 1/2: loss = 4.340239
ListNet epoch 2/2: loss = 4.304283
GRU fold 60/103 2024-08-27: fine-tune training (train=57626, test=194)
ListNet epoch 1/2: loss = 4.341772
ListNet epoch 2/2: loss = 4.310853
GRU fold 61/103 2024-09-03: fine-tune training (train=58596, test=194)
ListNet epoch 1/2: loss = 4.401270
ListNet epoch 2/2: loss = 4.330721
GRU fold 62/103 2024-09-10: fresh training (train=59566, test=194)
ListNet epoch 1/10: loss = 5.283025
ListNet epoch 2/10: loss = 5.200731
ListNet epoch 3/10: loss = 4.953195
ListNet epoch 4/10: loss = 4.749485
ListNet epoch 5/10: loss = 4.682455
ListNet epoch 6/10: loss = 4.653562
ListNet epoch 7/10: loss = 4.680304
ListNet epoch 8/10: loss = 4.641692
ListNet epoch 9/10: loss = 4.568403
ListNet epoch 10/10: loss = 4.503137
GRU fold 63/103 2024-09-17: fine-tune training (train=60536, test=194)
ListNet epoch 1/2: loss = 4.454379
ListNet epoch 2/2: loss = 4.488575
GRU fold 64/103 2024-09-24: fine-tune training (train=61506, test=194)
ListNet epoch 1/2: loss = 4.523167
ListNet epoch 2/2: loss = 4.469389
GRU fold 65/103 2024-10-01: fine-tune training (train=62476, test=194)
ListNet epoch 1/2: loss = 4.433058
ListNet epoch 2/2: loss = 4.431879
GRU fold 66/103 2024-10-08: fine-tune training (train=63446, test=194)
ListNet epoch 1/2: loss = 4.553622
ListNet epoch 2/2: loss = 4.482908
GRU fold 67/103 2024-10-15: fine-tune training (train=64416, test=194)
ListNet epoch 1/2: loss = 4.439071
ListNet epoch 2/2: loss = 4.432641
GRU fold 68/103 2024-10-22: fine-tune training (train=65386, test=194)
ListNet epoch 1/2: loss = 4.503429
ListNet epoch 2/2: loss = 4.465279
GRU fold 69/103 2024-10-29: fine-tune training (train=66356, test=194)
ListNet epoch 1/2: loss = 4.495311
ListNet epoch 2/2: loss = 4.409412
GRU fold 70/103 2024-11-05: fine-tune training (train=67326, test=194)
ListNet epoch 1/2: loss = 4.454218
ListNet epoch 2/2: loss = 4.475626
GRU fold 71/103 2024-11-12: fine-tune training (train=68296, test=194)
ListNet epoch 1/2: loss = 4.514606
ListNet epoch 2/2: loss = 4.492154
GRU fold 72/103 2024-11-19: fine-tune training (train=69266, test=194)
ListNet epoch 1/2: loss = 4.471909
ListNet epoch 2/2: loss = 4.529939
GRU fold 73/103 2024-11-26: fine-tune training (train=70236, test=194)
ListNet epoch 1/2: loss = 4.575613
ListNet epoch 2/2: loss = 4.485437
GRU fold 74/103 2024-12-03: fine-tune training (train=71206, test=194)
ListNet epoch 1/2: loss = 4.550240
ListNet epoch 2/2: loss = 4.490481
GRU fold 75/103 2024-12-10: fine-tune training (train=72176, test=194)
ListNet epoch 1/2: loss = 4.476329
ListNet epoch 2/2: loss = 4.488175
GRU fold 76/103 2024-12-17: fine-tune training (train=73146, test=194)
ListNet epoch 1/2: loss = 4.471105
ListNet epoch 2/2: loss = 4.430925
GRU fold 77/103 2024-12-24: fine-tune training (train=74116, test=194)
ListNet epoch 1/2: loss = 4.437160
ListNet epoch 2/2: loss = 4.469527
GRU fold 78/103 2024-12-31: fine-tune training (train=74698, test=194)
ListNet epoch 1/2: loss = 4.463573
ListNet epoch 2/2: loss = 4.444046
GRU fold 79/103 2025-01-07: fine-tune training (train=75474, test=194)
ListNet epoch 1/2: loss = 4.476400
ListNet epoch 2/2: loss = 4.464047
GRU fold 80/103 2025-01-14: fine-tune training (train=76444, test=194)
ListNet epoch 1/2: loss = 4.424672
ListNet epoch 2/2: loss = 4.410762
GRU fold 81/103 2025-01-21: fine-tune training (train=77414, test=195)
ListNet epoch 1/2: loss = 4.469156
ListNet epoch 2/2: loss = 4.393758
GRU fold 82/103 2025-01-28: fine-tune training (train=78192, test=195)
ListNet epoch 1/2: loss = 4.431895
ListNet epoch 2/2: loss = 4.416635
GRU fold 83/103 2025-02-04: fine-tune training (train=79167, test=195)
ListNet epoch 1/2: loss = 4.411975
ListNet epoch 2/2: loss = 4.376358
GRU fold 84/103 2025-02-11: fine-tune training (train=80142, test=195)
ListNet epoch 1/2: loss = 4.373572
ListNet epoch 2/2: loss = 4.402915
GRU fold 85/103 2025-02-18: fine-tune training (train=81117, test=195)
ListNet epoch 1/2: loss = 4.361653
ListNet epoch 2/2: loss = 4.351958
GRU fold 86/103 2025-02-25: fine-tune training (train=82092, test=195)
ListNet epoch 1/2: loss = 4.325565
ListNet epoch 2/2: loss = 4.360119
GRU fold 87/103 2025-03-04: fine-tune training (train=83067, test=195)
ListNet epoch 1/2: loss = 4.374310
ListNet epoch 2/2: loss = 4.350567
GRU fold 88/103 2025-03-11: fresh training (train=84042, test=195)
ListNet epoch 1/10: loss = 5.261026
ListNet epoch 2/10: loss = 5.151327
ListNet epoch 3/10: loss = 4.900985
ListNet epoch 4/10: loss = 4.709288
ListNet epoch 5/10: loss = 4.662533
ListNet epoch 6/10: loss = 4.617142
ListNet epoch 7/10: loss = 4.698867
ListNet epoch 8/10: loss = 4.612398
ListNet epoch 9/10: loss = 4.616802
ListNet epoch 10/10: loss = 4.715075
GRU fold 89/103 2025-03-18: fine-tune training (train=85017, test=195)
ListNet epoch 1/2: loss = 4.565438
ListNet epoch 2/2: loss = 4.536762
GRU fold 90/103 2025-03-25: fine-tune training (train=85992, test=195)
ListNet epoch 1/2: loss = 4.514937
ListNet epoch 2/2: loss = 4.522800
GRU fold 91/103 2025-04-01: fine-tune training (train=86967, test=195)
ListNet epoch 1/2: loss = 4.561833
ListNet epoch 2/2: loss = 4.571758
GRU fold 92/103 2025-04-08: fine-tune training (train=87942, test=195)
ListNet epoch 1/2: loss = 4.501092
ListNet epoch 2/2: loss = 4.518850
GRU fold 93/103 2025-04-15: fine-tune training (train=88917, test=195)
ListNet epoch 1/2: loss = 4.506951
ListNet epoch 2/2: loss = 4.479798
GRU fold 94/103 2025-04-22: fine-tune training (train=89502, test=195)
ListNet epoch 1/2: loss = 4.517413
ListNet epoch 2/2: loss = 4.592249
GRU fold 95/103 2025-04-29: fine-tune training (train=90282, test=195)
ListNet epoch 1/2: loss = 4.513472
ListNet epoch 2/2: loss = 4.446927
GRU fold 96/103 2025-05-06: fine-tune training (train=91257, test=195)
ListNet epoch 1/2: loss = 4.477632
ListNet epoch 2/2: loss = 4.497265
GRU fold 97/103 2025-05-13: fine-tune training (train=92232, test=195)
ListNet epoch 1/2: loss = 4.533076
ListNet epoch 2/2: loss = 4.555878
GRU fold 98/103 2025-05-20: fine-tune training (train=93207, test=195)
ListNet epoch 1/2: loss = 4.565468
ListNet epoch 2/2: loss = 4.575156
GRU fold 99/103 2025-05-27: fine-tune training (train=94182, test=195)
ListNet epoch 1/2: loss = 4.539676
ListNet epoch 2/2: loss = 4.584352
GRU fold 100/103 2025-06-03: fine-tune training (train=95157, test=195)
ListNet epoch 1/2: loss = 4.565739
ListNet epoch 2/2: loss = 4.580118
GRU fold 101/103 2025-06-10: fine-tune training (train=95937, test=195)
ListNet epoch 1/2: loss = 4.563232
ListNet epoch 2/2: loss = 4.545111
GRU fold 102/103 2025-06-17: fine-tune training (train=96912, test=195)
ListNet epoch 1/2: loss = 4.537020
ListNet epoch 2/2: loss = 4.598022
GRU fold 103/103 2025-06-24: fine-tune training (train=97887, test=197)
ListNet epoch 1/2: loss = 4.627260
ListNet epoch 2/2: loss = 4.564012

/mnt/c/Users/Gordon Li/Desktop/systematic_project/scripts/models/gru/tune_gru.py:88: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  daily_ic = preds.groupby("Date").apply(

4/6: IC = 0.01674 (raw_ic=0.01674, trained_folds=94, skipped_folds=9, coverage=91.3%)
GRU fold 1/103 2023-07-04: skipped (train=1880, test=188, reason=train_too_small)
GRU fold 2/103 2023-07-11: skipped (train=2820, test=188, reason=train_too_small)
GRU fold 3/103 2023-07-18: skipped (train=3760, test=188, reason=train_too_small)
GRU fold 4/103 2023-07-25: skipped (train=4700, test=188, reason=train_too_small)
GRU fold 5/103 2023-08-01: skipped (train=5640, test=189, reason=train_too_small)
GRU fold 6/103 2023-08-08: skipped (train=6581, test=189, reason=train_too_small)
GRU fold 7/103 2023-08-15: skipped (train=7526, test=189, reason=train_too_small)
GRU fold 8/103 2023-08-22: skipped (train=8471, test=189, reason=train_too_small)
GRU fold 9/103 2023-08-29: skipped (train=9416, test=189, reason=train_too_small)
GRU fold 10/103 2023-09-05: fresh training (train=10361, test=189)
ListNet epoch 1/10: loss = 5.292879
ListNet epoch 2/10: loss = 5.219213
ListNet epoch 3/10: loss = 5.162806
ListNet epoch 4/10: loss = 5.065553
ListNet epoch 5/10: loss = 5.029567
ListNet epoch 6/10: loss = 4.948656
ListNet epoch 7/10: loss = 4.879011
ListNet epoch 8/10: loss = 4.802946
ListNet epoch 9/10: loss = 4.786551
ListNet epoch 10/10: loss = 4.812016
GRU fold 11/103 2023-09-12: fine-tune training (train=11306, test=189)
ListNet epoch 1/2: loss = 4.796175
ListNet epoch 2/2: loss = 4.741543
GRU fold 12/103 2023-09-19: fine-tune training (train=12251, test=189)
ListNet epoch 1/2: loss = 4.728655
ListNet epoch 2/2: loss = 4.716445
GRU fold 13/103 2023-09-26: fine-tune training (train=13196, test=189)
ListNet epoch 1/2: loss = 4.743117
ListNet epoch 2/2: loss = 4.586496
GRU fold 14/103 2023-10-03: fine-tune training (train=14141, test=189)
ListNet epoch 1/2: loss = 4.644388
ListNet epoch 2/2: loss = 4.664775
GRU fold 15/103 2023-10-10: fine-tune training (train=15086, test=190)
ListNet epoch 1/2: loss = 4.632857
ListNet epoch 2/2: loss = 4.630539
GRU fold 16/103 2023-10-17: fine-tune training (train=16032, test=190)
ListNet epoch 1/2: loss = 4.700070
ListNet epoch 2/2: loss = 4.558314
GRU fold 17/103 2023-10-24: fine-tune training (train=16982, test=190)
ListNet epoch 1/2: loss = 4.590407
ListNet epoch 2/2: loss = 4.700748
GRU fold 18/103 2023-10-31: fine-tune training (train=17932, test=191)
ListNet epoch 1/2: loss = 4.794216
ListNet epoch 2/2: loss = 4.744571
GRU fold 19/103 2023-11-07: fine-tune training (train=18885, test=191)
ListNet epoch 1/2: loss = 4.677466
ListNet epoch 2/2: loss = 4.579308
GRU fold 20/103 2023-11-14: fine-tune training (train=19840, test=191)
ListNet epoch 1/2: loss = 4.583312
ListNet epoch 2/2: loss = 4.600034
GRU fold 21/103 2023-11-21: fine-tune training (train=20795, test=191)
ListNet epoch 1/2: loss = 4.638403
ListNet epoch 2/2: loss = 4.586652
GRU fold 22/103 2023-11-28: fine-tune training (train=21750, test=191)
ListNet epoch 1/2: loss = 4.619633
ListNet epoch 2/2: loss = 4.527363
GRU fold 23/103 2023-12-05: fine-tune training (train=22705, test=191)
ListNet epoch 1/2: loss = 4.516781
ListNet epoch 2/2: loss = 4.379549
GRU fold 24/103 2023-12-12: fine-tune training (train=23660, test=191)
ListNet epoch 1/2: loss = 4.504156
ListNet epoch 2/2: loss = 4.367970
GRU fold 25/103 2023-12-19: fine-tune training (train=24615, test=191)
ListNet epoch 1/2: loss = 4.418796
ListNet epoch 2/2: loss = 4.370943
GRU fold 26/103 2024-01-02: fine-tune training (train=25952, test=191)
ListNet epoch 1/2: loss = 4.415779
ListNet epoch 2/2: loss = 4.361002
GRU fold 27/103 2024-01-09: fine-tune training (train=26907, test=191)
ListNet epoch 1/2: loss = 4.386422
ListNet epoch 2/2: loss = 4.461556
GRU fold 28/103 2024-01-16: fine-tune training (train=27862, test=191)
ListNet epoch 1/2: loss = 4.425137
ListNet epoch 2/2: loss = 4.444222
GRU fold 29/103 2024-01-23: fine-tune training (train=28817, test=191)
ListNet epoch 1/2: loss = 4.390280
ListNet epoch 2/2: loss = 4.392963
GRU fold 30/103 2024-01-30: fine-tune training (train=29581, test=191)
ListNet epoch 1/2: loss = 4.414431
ListNet epoch 2/2: loss = 4.491270
GRU fold 31/103 2024-02-06: fine-tune training (train=30536, test=191)
ListNet epoch 1/2: loss = 4.419778
ListNet epoch 2/2: loss = 4.370037
GRU fold 32/103 2024-02-13: fine-tune training (train=31491, test=191)
ListNet epoch 1/2: loss = 4.418806
ListNet epoch 2/2: loss = 4.424532
GRU fold 33/103 2024-02-20: fine-tune training (train=32446, test=191)
ListNet epoch 1/2: loss = 4.462708
ListNet epoch 2/2: loss = 4.439968
GRU fold 34/103 2024-02-27: fine-tune training (train=33401, test=191)
ListNet epoch 1/2: loss = 4.433303
ListNet epoch 2/2: loss = 4.436077
GRU fold 35/103 2024-03-05: fine-tune training (train=34356, test=191)
ListNet epoch 1/2: loss = 4.530417
ListNet epoch 2/2: loss = 4.439855
GRU fold 36/103 2024-03-12: fresh training (train=35311, test=191)
ListNet epoch 1/10: loss = 5.275338
ListNet epoch 2/10: loss = 5.120057
ListNet epoch 3/10: loss = 4.876660
ListNet epoch 4/10: loss = 4.662114
ListNet epoch 5/10: loss = 4.655400
ListNet epoch 6/10: loss = 4.558095
ListNet epoch 7/10: loss = 4.534139
ListNet epoch 8/10: loss = 4.681955
ListNet epoch 9/10: loss = 4.524254
ListNet epoch 10/10: loss = 4.436651
GRU fold 37/103 2024-03-19: fine-tune training (train=36266, test=191)
ListNet epoch 1/2: loss = 4.432489
ListNet epoch 2/2: loss = 4.468649
GRU fold 38/103 2024-03-26: fine-tune training (train=37221, test=191)
ListNet epoch 1/2: loss = 4.453253
ListNet epoch 2/2: loss = 4.401798
GRU fold 39/103 2024-04-02: fine-tune training (train=37794, test=191)
ListNet epoch 1/2: loss = 4.418106
ListNet epoch 2/2: loss = 4.421161
GRU fold 40/103 2024-04-09: fine-tune training (train=38749, test=192)
ListNet epoch 1/2: loss = 4.407330
ListNet epoch 2/2: loss = 4.385468
GRU fold 41/103 2024-04-16: fine-tune training (train=39706, test=192)
ListNet epoch 1/2: loss = 4.363221
ListNet epoch 2/2: loss = 4.334457
GRU fold 42/103 2024-04-23: fine-tune training (train=40666, test=192)
ListNet epoch 1/2: loss = 4.339288
ListNet epoch 2/2: loss = 4.351723
GRU fold 43/103 2024-04-30: fine-tune training (train=41434, test=192)
ListNet epoch 1/2: loss = 4.318346
ListNet epoch 2/2: loss = 4.506057
GRU fold 44/103 2024-05-07: fine-tune training (train=42394, test=192)
ListNet epoch 1/2: loss = 4.322932
ListNet epoch 2/2: loss = 4.346306
GRU fold 45/103 2024-05-14: fine-tune training (train=43354, test=192)
ListNet epoch 1/2: loss = 4.394379
ListNet epoch 2/2: loss = 4.341320
GRU fold 46/103 2024-05-21: fine-tune training (train=44314, test=192)
ListNet epoch 1/2: loss = 4.391625
ListNet epoch 2/2: loss = 4.422413
GRU fold 47/103 2024-05-28: fine-tune training (train=45274, test=192)
ListNet epoch 1/2: loss = 4.484230
ListNet epoch 2/2: loss = 4.531664
GRU fold 48/103 2024-06-04: fine-tune training (train=46234, test=192)
ListNet epoch 1/2: loss = 4.422690
ListNet epoch 2/2: loss = 4.483005
GRU fold 49/103 2024-06-11: fine-tune training (train=47002, test=192)
ListNet epoch 1/2: loss = 4.360739
ListNet epoch 2/2: loss = 4.343153
GRU fold 50/103 2024-06-18: fine-tune training (train=47962, test=192)
ListNet epoch 1/2: loss = 4.393627
ListNet epoch 2/2: loss = 4.447814
GRU fold 51/103 2024-06-25: fine-tune training (train=48922, test=193)
ListNet epoch 1/2: loss = 4.440613
ListNet epoch 2/2: loss = 4.363339
GRU fold 52/103 2024-07-02: fine-tune training (train=49886, test=193)
ListNet epoch 1/2: loss = 4.391156
ListNet epoch 2/2: loss = 4.385774
GRU fold 53/103 2024-07-09: fine-tune training (train=50851, test=193)
ListNet epoch 1/2: loss = 4.340584
ListNet epoch 2/2: loss = 4.444985
GRU fold 54/103 2024-07-16: fine-tune training (train=51816, test=193)
ListNet epoch 1/2: loss = 4.345338
ListNet epoch 2/2: loss = 4.376025
GRU fold 55/103 2024-07-23: fine-tune training (train=52781, test=193)
ListNet epoch 1/2: loss = 4.328637
ListNet epoch 2/2: loss = 4.424612
GRU fold 56/103 2024-07-30: fine-tune training (train=53746, test=194)
ListNet epoch 1/2: loss = 4.324386
ListNet epoch 2/2: loss = 4.318145
GRU fold 57/103 2024-08-06: fine-tune training (train=54716, test=194)
ListNet epoch 1/2: loss = 4.253196
ListNet epoch 2/2: loss = 4.426538
GRU fold 58/103 2024-08-13: fine-tune training (train=55686, test=194)
ListNet epoch 1/2: loss = 4.267083
ListNet epoch 2/2: loss = 4.282420
GRU fold 59/103 2024-08-20: fine-tune training (train=56656, test=194)
ListNet epoch 1/2: loss = 4.202366
ListNet epoch 2/2: loss = 4.288315
GRU fold 60/103 2024-08-27: fine-tune training (train=57626, test=194)
ListNet epoch 1/2: loss = 4.294626
ListNet epoch 2/2: loss = 4.280469
GRU fold 61/103 2024-09-03: fine-tune training (train=58596, test=194)
ListNet epoch 1/2: loss = 4.307790
ListNet epoch 2/2: loss = 4.215761
GRU fold 62/103 2024-09-10: fresh training (train=59566, test=194)
ListNet epoch 1/10: loss = 5.259083
ListNet epoch 2/10: loss = 5.089638
ListNet epoch 3/10: loss = 4.868587
ListNet epoch 4/10: loss = 4.743957
ListNet epoch 5/10: loss = 4.649809
ListNet epoch 6/10: loss = 4.479763
ListNet epoch 7/10: loss = 4.562101
ListNet epoch 8/10: loss = 4.365589
ListNet epoch 9/10: loss = 4.620337
ListNet epoch 10/10: loss = 4.526308
GRU fold 63/103 2024-09-17: fine-tune training (train=60536, test=194)
ListNet epoch 1/2: loss = 4.476231
ListNet epoch 2/2: loss = 4.589390
GRU fold 64/103 2024-09-24: fine-tune training (train=61506, test=194)
ListNet epoch 1/2: loss = 4.596307
ListNet epoch 2/2: loss = 4.821043
GRU fold 65/103 2024-10-01: fine-tune training (train=62476, test=194)
ListNet epoch 1/2: loss = 4.511035
ListNet epoch 2/2: loss = 4.590119
GRU fold 66/103 2024-10-08: fine-tune training (train=63446, test=194)
ListNet epoch 1/2: loss = 4.623013
ListNet epoch 2/2: loss = 4.834679
GRU fold 67/103 2024-10-15: fine-tune training (train=64416, test=194)
ListNet epoch 1/2: loss = 4.683654
ListNet epoch 2/2: loss = 4.623902
GRU fold 68/103 2024-10-22: fine-tune training (train=65386, test=194)
ListNet epoch 1/2: loss = 4.428595
ListNet epoch 2/2: loss = 4.414051
GRU fold 69/103 2024-10-29: fine-tune training (train=66356, test=194)
ListNet epoch 1/2: loss = 4.730013
ListNet epoch 2/2: loss = 4.776377
GRU fold 70/103 2024-11-05: fine-tune training (train=67326, test=194)
ListNet epoch 1/2: loss = 4.476395
ListNet epoch 2/2: loss = 4.490256
GRU fold 71/103 2024-11-12: fine-tune training (train=68296, test=194)
ListNet epoch 1/2: loss = 4.457927
ListNet epoch 2/2: loss = 4.539855
GRU fold 72/103 2024-11-19: fine-tune training (train=69266, test=194)
ListNet epoch 1/2: loss = 4.554040
ListNet epoch 2/2: loss = 4.939667
GRU fold 73/103 2024-11-26: fine-tune training (train=70236, test=194)
ListNet epoch 1/2: loss = 4.553578
ListNet epoch 2/2: loss = 4.545087
GRU fold 74/103 2024-12-03: fine-tune training (train=71206, test=194)
ListNet epoch 1/2: loss = 4.633702
ListNet epoch 2/2: loss = 4.619984
GRU fold 75/103 2024-12-10: fine-tune training (train=72176, test=194)
ListNet epoch 1/2: loss = 4.628281
ListNet epoch 2/2: loss = 4.600177
GRU fold 76/103 2024-12-17: fine-tune training (train=73146, test=194)
ListNet epoch 1/2: loss = 4.614803
ListNet epoch 2/2: loss = 4.643000
GRU fold 77/103 2024-12-24: fine-tune training (train=74116, test=194)
ListNet epoch 1/2: loss = 4.682338
ListNet epoch 2/2: loss = 4.615437
GRU fold 78/103 2024-12-31: fine-tune training (train=74698, test=194)
ListNet epoch 1/2: loss = 4.597389
ListNet epoch 2/2: loss = 4.603228
GRU fold 79/103 2025-01-07: fine-tune training (train=75474, test=194)
ListNet epoch 1/2: loss = 4.620255
ListNet epoch 2/2: loss = 4.582139
GRU fold 80/103 2025-01-14: fine-tune training (train=76444, test=194)
ListNet epoch 1/2: loss = 4.589256
ListNet epoch 2/2: loss = 4.592074
GRU fold 81/103 2025-01-21: fine-tune training (train=77414, test=195)
ListNet epoch 1/2: loss = 4.543623
ListNet epoch 2/2: loss = 4.624383
GRU fold 82/103 2025-01-28: fine-tune training (train=78192, test=195)
ListNet epoch 1/2: loss = 4.505396
ListNet epoch 2/2: loss = 4.512135
GRU fold 83/103 2025-02-04: fine-tune training (train=79167, test=195)
ListNet epoch 1/2: loss = 4.535397
ListNet epoch 2/2: loss = 4.536696
GRU fold 84/103 2025-02-11: fine-tune training (train=80142, test=195)
ListNet epoch 1/2: loss = 4.522534
ListNet epoch 2/2: loss = 4.519406
GRU fold 85/103 2025-02-18: fine-tune training (train=81117, test=195)
ListNet epoch 1/2: loss = 4.608535
ListNet epoch 2/2: loss = 4.728852
GRU fold 86/103 2025-02-25: fine-tune training (train=82092, test=195)
ListNet epoch 1/2: loss = 4.463144
ListNet epoch 2/2: loss = 4.508534
GRU fold 87/103 2025-03-04: fine-tune training (train=83067, test=195)
ListNet epoch 1/2: loss = 4.580353
ListNet epoch 2/2: loss = 4.534721
GRU fold 88/103 2025-03-11: fresh training (train=84042, test=195)
ListNet epoch 1/10: loss = 5.265244
ListNet epoch 2/10: loss = 5.226348
ListNet epoch 3/10: loss = 5.148590
ListNet epoch 4/10: loss = 5.081012
ListNet epoch 5/10: loss = 4.943488
ListNet epoch 6/10: loss = 5.061560
ListNet epoch 7/10: loss = 5.008971
ListNet epoch 8/10: loss = 5.072285
Early stopping at epoch 8/10
GRU fold 89/103 2025-03-18: fine-tune training (train=85017, test=195)
ListNet epoch 1/2: loss = 5.097917
ListNet epoch 2/2: loss = 4.961211
GRU fold 90/103 2025-03-25: fine-tune training (train=85992, test=195)
ListNet epoch 1/2: loss = 4.901417
ListNet epoch 2/2: loss = 4.833138
GRU fold 91/103 2025-04-01: fine-tune training (train=86967, test=195)
ListNet epoch 1/2: loss = 4.788335
ListNet epoch 2/2: loss = 4.812334
GRU fold 92/103 2025-04-08: fine-tune training (train=87942, test=195)
ListNet epoch 1/2: loss = 4.878010
ListNet epoch 2/2: loss = 5.287670
GRU fold 93/103 2025-04-15: fine-tune training (train=88917, test=195)
ListNet epoch 1/2: loss = 4.837281
ListNet epoch 2/2: loss = 4.843467
GRU fold 94/103 2025-04-22: fine-tune training (train=89502, test=195)
ListNet epoch 1/2: loss = 4.726352
ListNet epoch 2/2: loss = 4.924949
GRU fold 95/103 2025-04-29: fine-tune training (train=90282, test=195)
ListNet epoch 1/2: loss = 4.809499
ListNet epoch 2/2: loss = 4.777382
GRU fold 96/103 2025-05-06: fine-tune training (train=91257, test=195)
ListNet epoch 1/2: loss = 4.685842
ListNet epoch 2/2: loss = 4.928715
GRU fold 97/103 2025-05-13: fine-tune training (train=92232, test=195)
ListNet epoch 1/2: loss = 4.722255
ListNet epoch 2/2: loss = 4.715851
GRU fold 98/103 2025-05-20: fine-tune training (train=93207, test=195)
ListNet epoch 1/2: loss = 4.815745
ListNet epoch 2/2: loss = 5.187313
GRU fold 99/103 2025-05-27: fine-tune training (train=94182, test=195)
ListNet epoch 1/2: loss = 4.736034
ListNet epoch 2/2: loss = 4.808374
GRU fold 100/103 2025-06-03: fine-tune training (train=95157, test=195)
ListNet epoch 1/2: loss = 4.801257
ListNet epoch 2/2: loss = 4.849782
GRU fold 101/103 2025-06-10: fine-tune training (train=95937, test=195)
ListNet epoch 1/2: loss = 4.845540
ListNet epoch 2/2: loss = 4.741915
GRU fold 102/103 2025-06-17: fine-tune training (train=96912, test=195)
ListNet epoch 1/2: loss = 4.762574
ListNet epoch 2/2: loss = 4.753594
GRU fold 103/103 2025-06-24: fine-tune training (train=97887, test=197)
ListNet epoch 1/2: loss = 4.932146
ListNet epoch 2/2: loss = 4.932504

/mnt/c/Users/Gordon Li/Desktop/systematic_project/scripts/models/gru/tune_gru.py:88: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  daily_ic = preds.groupby("Date").apply(

5/6: IC = 0.01889 (raw_ic=0.01889, trained_folds=94, skipped_folds=9, coverage=91.3%)
GRU fold 1/103 2023-07-04: skipped (train=1880, test=188, reason=train_too_small)
GRU fold 2/103 2023-07-11: skipped (train=2820, test=188, reason=train_too_small)
GRU fold 3/103 2023-07-18: skipped (train=3760, test=188, reason=train_too_small)
GRU fold 4/103 2023-07-25: skipped (train=4700, test=188, reason=train_too_small)
GRU fold 5/103 2023-08-01: skipped (train=5640, test=189, reason=train_too_small)
GRU fold 6/103 2023-08-08: skipped (train=6581, test=189, reason=train_too_small)
GRU fold 7/103 2023-08-15: skipped (train=7526, test=189, reason=train_too_small)
GRU fold 8/103 2023-08-22: skipped (train=8471, test=189, reason=train_too_small)
GRU fold 9/103 2023-08-29: skipped (train=9416, test=189, reason=train_too_small)
GRU fold 10/103 2023-09-05: fresh training (train=10361, test=189)
ListNet epoch 1/10: loss = 5.299976
ListNet epoch 2/10: loss = 5.321143
ListNet epoch 3/10: loss = 5.324509
ListNet epoch 4/10: loss = 5.285092
ListNet epoch 5/10: loss = 5.278080
ListNet epoch 6/10: loss = 5.229078
ListNet epoch 7/10: loss = 5.262044
ListNet epoch 8/10: loss = 5.270863
ListNet epoch 9/10: loss = 5.270525
Early stopping at epoch 9/10
GRU fold 11/103 2023-09-12: fine-tune training (train=11306, test=189)
ListNet epoch 1/2: loss = 5.255720
ListNet epoch 2/2: loss = 5.282610
GRU fold 12/103 2023-09-19: fine-tune training (train=12251, test=189)
ListNet epoch 1/2: loss = 5.243581
ListNet epoch 2/2: loss = 5.255455
GRU fold 13/103 2023-09-26: fine-tune training (train=13196, test=189)
ListNet epoch 1/2: loss = 5.238459
ListNet epoch 2/2: loss = 5.253908
GRU fold 14/103 2023-10-03: fine-tune training (train=14141, test=189)
ListNet epoch 1/2: loss = 5.216662
ListNet epoch 2/2: loss = 5.186951
GRU fold 15/103 2023-10-10: fine-tune training (train=15086, test=190)
ListNet epoch 1/2: loss = 5.182344
ListNet epoch 2/2: loss = 5.205933
GRU fold 16/103 2023-10-17: fine-tune training (train=16032, test=190)
ListNet epoch 1/2: loss = 5.159230
ListNet epoch 2/2: loss = 5.173766
GRU fold 17/103 2023-10-24: fine-tune training (train=16982, test=190)
ListNet epoch 1/2: loss = 5.144605
ListNet epoch 2/2: loss = 5.068283
GRU fold 18/103 2023-10-31: fine-tune training (train=17932, test=191)
ListNet epoch 1/2: loss = 5.116921
ListNet epoch 2/2: loss = 5.043090
GRU fold 19/103 2023-11-07: fine-tune training (train=18885, test=191)
ListNet epoch 1/2: loss = 4.992980
ListNet epoch 2/2: loss = 5.001151
GRU fold 20/103 2023-11-14: fine-tune training (train=19840, test=191)
ListNet epoch 1/2: loss = 4.988941
ListNet epoch 2/2: loss = 4.930199
GRU fold 21/103 2023-11-21: fine-tune training (train=20795, test=191)
ListNet epoch 1/2: loss = 4.890214
ListNet epoch 2/2: loss = 4.893194
GRU fold 22/103 2023-11-28: fine-tune training (train=21750, test=191)
ListNet epoch 1/2: loss = 4.836891
ListNet epoch 2/2: loss = 4.832377
GRU fold 23/103 2023-12-05: fine-tune training (train=22705, test=191)
ListNet epoch 1/2: loss = 4.747026
ListNet epoch 2/2: loss = 4.784838
GRU fold 24/103 2023-12-12: fine-tune training (train=23660, test=191)
ListNet epoch 1/2: loss = 4.682282
ListNet epoch 2/2: loss = 4.665726
GRU fold 25/103 2023-12-19: fine-tune training (train=24615, test=191)
ListNet epoch 1/2: loss = 4.650513
ListNet epoch 2/2: loss = 4.669990
GRU fold 26/103 2024-01-02: fine-tune training (train=25952, test=191)
ListNet epoch 1/2: loss = 4.631538
ListNet epoch 2/2: loss = 4.652092
GRU fold 27/103 2024-01-09: fine-tune training (train=26907, test=191)
ListNet epoch 1/2: loss = 4.576453
ListNet epoch 2/2: loss = 4.551408
GRU fold 28/103 2024-01-16: fine-tune training (train=27862, test=191)
ListNet epoch 1/2: loss = 4.526447
ListNet epoch 2/2: loss = 4.521903
GRU fold 29/103 2024-01-23: fine-tune training (train=28817, test=191)
ListNet epoch 1/2: loss = 4.533030
ListNet epoch 2/2: loss = 4.512031
GRU fold 30/103 2024-01-30: fine-tune training (train=29581, test=191)
ListNet epoch 1/2: loss = 4.466065
ListNet epoch 2/2: loss = 4.478415
GRU fold 31/103 2024-02-06: fine-tune training (train=30536, test=191)
ListNet epoch 1/2: loss = 4.426045
ListNet epoch 2/2: loss = 4.471434
GRU fold 32/103 2024-02-13: fine-tune training (train=31491, test=191)
ListNet epoch 1/2: loss = 4.382630
ListNet epoch 2/2: loss = 4.410323
GRU fold 33/103 2024-02-20: fine-tune training (train=32446, test=191)
ListNet epoch 1/2: loss = 4.419043
ListNet epoch 2/2: loss = 4.393311
GRU fold 34/103 2024-02-27: fine-tune training (train=33401, test=191)
ListNet epoch 1/2: loss = 4.463899
ListNet epoch 2/2: loss = 4.462145
GRU fold 35/103 2024-03-05: fine-tune training (train=34356, test=191)
ListNet epoch 1/2: loss = 4.416064
ListNet epoch 2/2: loss = 4.413019
GRU fold 36/103 2024-03-12: fresh training (train=35311, test=191)
ListNet epoch 1/10: loss = 5.276260
ListNet epoch 2/10: loss = 5.299320
ListNet epoch 3/10: loss = 5.280119
ListNet epoch 4/10: loss = 5.211025
ListNet epoch 5/10: loss = 5.200419
ListNet epoch 6/10: loss = 5.137262
ListNet epoch 7/10: loss = 5.097594
ListNet epoch 8/10: loss = 5.048965
ListNet epoch 9/10: loss = 4.947349
ListNet epoch 10/10: loss = 4.881479
GRU fold 37/103 2024-03-19: fine-tune training (train=36266, test=191)
ListNet epoch 1/2: loss = 4.810651
ListNet epoch 2/2: loss = 4.758393
GRU fold 38/103 2024-03-26: fine-tune training (train=37221, test=191)
ListNet epoch 1/2: loss = 4.682109
ListNet epoch 2/2: loss = 4.648512
GRU fold 39/103 2024-04-02: fine-tune training (train=37794, test=191)
ListNet epoch 1/2: loss = 4.582205
ListNet epoch 2/2: loss = 4.584925
GRU fold 40/103 2024-04-09: fine-tune training (train=38749, test=192)
ListNet epoch 1/2: loss = 4.531898
ListNet epoch 2/2: loss = 4.551346
GRU fold 41/103 2024-04-16: fine-tune training (train=39706, test=192)
ListNet epoch 1/2: loss = 4.498104
ListNet epoch 2/2: loss = 4.531099
GRU fold 42/103 2024-04-23: fine-tune training (train=40666, test=192)
ListNet epoch 1/2: loss = 4.439028
ListNet epoch 2/2: loss = 4.479627
GRU fold 43/103 2024-04-30: fine-tune training (train=41434, test=192)
ListNet epoch 1/2: loss = 4.480450
ListNet epoch 2/2: loss = 4.357055
GRU fold 44/103 2024-05-07: fine-tune training (train=42394, test=192)
ListNet epoch 1/2: loss = 4.418114
ListNet epoch 2/2: loss = 4.397243
GRU fold 45/103 2024-05-14: fine-tune training (train=43354, test=192)
ListNet epoch 1/2: loss = 4.383309
ListNet epoch 2/2: loss = 4.494331
GRU fold 46/103 2024-05-21: fine-tune training (train=44314, test=192)
ListNet epoch 1/2: loss = 4.508326
ListNet epoch 2/2: loss = 4.444088
GRU fold 47/103 2024-05-28: fine-tune training (train=45274, test=192)
ListNet epoch 1/2: loss = 4.437340
ListNet epoch 2/2: loss = 4.434864
GRU fold 48/103 2024-06-04: fine-tune training (train=46234, test=192)
ListNet epoch 1/2: loss = 4.458692
ListNet epoch 2/2: loss = 4.408073
GRU fold 49/103 2024-06-11: fine-tune training (train=47002, test=192)
ListNet epoch 1/2: loss = 4.493694
ListNet epoch 2/2: loss = 4.457890
GRU fold 50/103 2024-06-18: fine-tune training (train=47962, test=192)
ListNet epoch 1/2: loss = 4.381614
ListNet epoch 2/2: loss = 4.487576
GRU fold 51/103 2024-06-25: fine-tune training (train=48922, test=193)
ListNet epoch 1/2: loss = 4.429772
ListNet epoch 2/2: loss = 4.372727
GRU fold 52/103 2024-07-02: fine-tune training (train=49886, test=193)
ListNet epoch 1/2: loss = 4.319908
ListNet epoch 2/2: loss = 4.376183
GRU fold 53/103 2024-07-09: fine-tune training (train=50851, test=193)
ListNet epoch 1/2: loss = 4.407817
ListNet epoch 2/2: loss = 4.336720
GRU fold 54/103 2024-07-16: fine-tune training (train=51816, test=193)
ListNet epoch 1/2: loss = 4.339916
ListNet epoch 2/2: loss = 4.469979
GRU fold 55/103 2024-07-23: fine-tune training (train=52781, test=193)
ListNet epoch 1/2: loss = 4.381160
ListNet epoch 2/2: loss = 4.389264
GRU fold 56/103 2024-07-30: fine-tune training (train=53746, test=194)
ListNet epoch 1/2: loss = 4.331593
ListNet epoch 2/2: loss = 4.324266
GRU fold 57/103 2024-08-06: fine-tune training (train=54716, test=194)
ListNet epoch 1/2: loss = 4.367988
ListNet epoch 2/2: loss = 4.320193
GRU fold 58/103 2024-08-13: fine-tune training (train=55686, test=194)
ListNet epoch 1/2: loss = 4.366185
ListNet epoch 2/2: loss = 4.234483
GRU fold 59/103 2024-08-20: fine-tune training (train=56656, test=194)
ListNet epoch 1/2: loss = 4.197882
ListNet epoch 2/2: loss = 4.287932
GRU fold 60/103 2024-08-27: fine-tune training (train=57626, test=194)
ListNet epoch 1/2: loss = 4.258828
ListNet epoch 2/2: loss = 4.225919
GRU fold 61/103 2024-09-03: fine-tune training (train=58596, test=194)
ListNet epoch 1/2: loss = 4.245758
ListNet epoch 2/2: loss = 4.239843
GRU fold 62/103 2024-09-10: fresh training (train=59566, test=194)
ListNet epoch 1/10: loss = 5.326157
ListNet epoch 2/10: loss = 5.296950
ListNet epoch 3/10: loss = 5.288853
ListNet epoch 4/10: loss = 5.282825
ListNet epoch 5/10: loss = 5.231357
ListNet epoch 6/10: loss = 5.175013
ListNet epoch 7/10: loss = 5.109444
ListNet epoch 8/10: loss = 5.012079
ListNet epoch 9/10: loss = 4.941796
ListNet epoch 10/10: loss = 4.870268
GRU fold 63/103 2024-09-17: fine-tune training (train=60536, test=194)
ListNet epoch 1/2: loss = 4.791280
ListNet epoch 2/2: loss = 4.738155
GRU fold 64/103 2024-09-24: fine-tune training (train=61506, test=194)
ListNet epoch 1/2: loss = 4.689541
ListNet epoch 2/2: loss = 4.669151
GRU fold 65/103 2024-10-01: fine-tune training (train=62476, test=194)
ListNet epoch 1/2: loss = 4.623021
ListNet epoch 2/2: loss = 4.634490
GRU fold 66/103 2024-10-08: fine-tune training (train=63446, test=194)
ListNet epoch 1/2: loss = 4.581349
ListNet epoch 2/2: loss = 4.632173
GRU fold 67/103 2024-10-15: fine-tune training (train=64416, test=194)
ListNet epoch 1/2: loss = 4.554820
ListNet epoch 2/2: loss = 4.595232
GRU fold 68/103 2024-10-22: fine-tune training (train=65386, test=194)
ListNet epoch 1/2: loss = 4.556982
ListNet epoch 2/2: loss = 4.622353
GRU fold 69/103 2024-10-29: fine-tune training (train=66356, test=194)
ListNet epoch 1/2: loss = 4.559205
ListNet epoch 2/2: loss = 4.569635
GRU fold 70/103 2024-11-05: fine-tune training (train=67326, test=194)
ListNet epoch 1/2: loss = 4.594359
ListNet epoch 2/2: loss = 4.586983
GRU fold 71/103 2024-11-12: fine-tune training (train=68296, test=194)
ListNet epoch 1/2: loss = 4.600056
ListNet epoch 2/2: loss = 4.667304
GRU fold 72/103 2024-11-19: fine-tune training (train=69266, test=194)
ListNet epoch 1/2: loss = 4.589443
ListNet epoch 2/2: loss = 4.639060
GRU fold 73/103 2024-11-26: fine-tune training (train=70236, test=194)
ListNet epoch 1/2: loss = 4.615687
ListNet epoch 2/2: loss = 4.618553
GRU fold 74/103 2024-12-03: fine-tune training (train=71206, test=194)
ListNet epoch 1/2: loss = 4.616376
ListNet epoch 2/2: loss = 4.618194
GRU fold 75/103 2024-12-10: fine-tune training (train=72176, test=194)
ListNet epoch 1/2: loss = 4.625892
ListNet epoch 2/2: loss = 4.631003
GRU fold 76/103 2024-12-17: fine-tune training (train=73146, test=194)
ListNet epoch 1/2: loss = 4.676265
ListNet epoch 2/2: loss = 4.612834
GRU fold 77/103 2024-12-24: fine-tune training (train=74116, test=194)
ListNet epoch 1/2: loss = 4.616065
ListNet epoch 2/2: loss = 4.587237
GRU fold 78/103 2024-12-31: fine-tune training (train=74698, test=194)
ListNet epoch 1/2: loss = 4.609346
ListNet epoch 2/2: loss = 4.581905
GRU fold 79/103 2025-01-07: fine-tune training (train=75474, test=194)
ListNet epoch 1/2: loss = 4.564772
ListNet epoch 2/2: loss = 4.552008
GRU fold 80/103 2025-01-14: fine-tune training (train=76444, test=194)
ListNet epoch 1/2: loss = 4.563247
ListNet epoch 2/2: loss = 4.595776
GRU fold 81/103 2025-01-21: fine-tune training (train=77414, test=195)
ListNet epoch 1/2: loss = 4.516048
ListNet epoch 2/2: loss = 4.629211
GRU fold 82/103 2025-01-28: fine-tune training (train=78192, test=195)
ListNet epoch 1/2: loss = 4.579807
ListNet epoch 2/2: loss = 4.578992
GRU fold 83/103 2025-02-04: fine-tune training (train=79167, test=195)
ListNet epoch 1/2: loss = 4.639620
ListNet epoch 2/2: loss = 4.632754
GRU fold 84/103 2025-02-11: fine-tune training (train=80142, test=195)
ListNet epoch 1/2: loss = 4.601001
ListNet epoch 2/2: loss = 4.572609
GRU fold 85/103 2025-02-18: fine-tune training (train=81117, test=195)
ListNet epoch 1/2: loss = 4.545448
ListNet epoch 2/2: loss = 4.609148
GRU fold 86/103 2025-02-25: fine-tune training (train=82092, test=195)
ListNet epoch 1/2: loss = 4.548789
ListNet epoch 2/2: loss = 4.541488
GRU fold 87/103 2025-03-04: fine-tune training (train=83067, test=195)
ListNet epoch 1/2: loss = 4.558842
ListNet epoch 2/2: loss = 4.497951
GRU fold 88/103 2025-03-11: fresh training (train=84042, test=195)
ListNet epoch 1/10: loss = 5.286505
ListNet epoch 2/10: loss = 5.316695
ListNet epoch 3/10: loss = 5.299584
ListNet epoch 4/10: loss = 5.285941
ListNet epoch 5/10: loss = 5.302650
ListNet epoch 6/10: loss = 5.302894
ListNet epoch 7/10: loss = 5.263372
ListNet epoch 8/10: loss = 5.285567
ListNet epoch 9/10: loss = 5.225604
ListNet epoch 10/10: loss = 5.236364
GRU fold 89/103 2025-03-18: fine-tune training (train=85017, test=195)
ListNet epoch 1/2: loss = 5.188621
ListNet epoch 2/2: loss = 5.184700
GRU fold 90/103 2025-03-25: fine-tune training (train=85992, test=195)
ListNet epoch 1/2: loss = 5.172311
ListNet epoch 2/2: loss = 5.160488
GRU fold 91/103 2025-04-01: fine-tune training (train=86967, test=195)
ListNet epoch 1/2: loss = 5.118398
ListNet epoch 2/2: loss = 5.154794
GRU fold 92/103 2025-04-08: fine-tune training (train=87942, test=195)
ListNet epoch 1/2: loss = 5.120149
ListNet epoch 2/2: loss = 5.073155
GRU fold 93/103 2025-04-15: fine-tune training (train=88917, test=195)
ListNet epoch 1/2: loss = 5.084889
ListNet epoch 2/2: loss = 5.044196
GRU fold 94/103 2025-04-22: fine-tune training (train=89502, test=195)
ListNet epoch 1/2: loss = 5.054504
ListNet epoch 2/2: loss = 5.041403
GRU fold 95/103 2025-04-29: fine-tune training (train=90282, test=195)
ListNet epoch 1/2: loss = 5.003193
ListNet epoch 2/2: loss = 5.016982
GRU fold 96/103 2025-05-06: fine-tune training (train=91257, test=195)
ListNet epoch 1/2: loss = 5.009035
ListNet epoch 2/2: loss = 5.001449
GRU fold 97/103 2025-05-13: fine-tune training (train=92232, test=195)
ListNet epoch 1/2: loss = 4.995472
ListNet epoch 2/2: loss = 4.995113
GRU fold 98/103 2025-05-20: fine-tune training (train=93207, test=195)
ListNet epoch 1/2: loss = 4.950486
ListNet epoch 2/2: loss = 4.942844
GRU fold 99/103 2025-05-27: fine-tune training (train=94182, test=195)
ListNet epoch 1/2: loss = 4.934570
ListNet epoch 2/2: loss = 4.966539
GRU fold 100/103 2025-06-03: fine-tune training (train=95157, test=195)
ListNet epoch 1/2: loss = 4.930402
ListNet epoch 2/2: loss = 4.913631
GRU fold 101/103 2025-06-10: fine-tune training (train=95937, test=195)
ListNet epoch 1/2: loss = 4.924173
ListNet epoch 2/2: loss = 4.879144
GRU fold 102/103 2025-06-17: fine-tune training (train=96912, test=195)
ListNet epoch 1/2: loss = 4.893872
ListNet epoch 2/2: loss = 4.907522
GRU fold 103/103 2025-06-24: fine-tune training (train=97887, test=197)
ListNet epoch 1/2: loss = 4.873340
ListNet epoch 2/2: loss = 4.877785
6/6: IC = 0.01765 (raw_ic=0.01765, trained_folds=94, skipped_folds=9, coverage=91.3%)

/mnt/c/Users/Gordon Li/Desktop/systematic_project/scripts/models/gru/tune_gru.py:88: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  daily_ic = preds.groupby("Date").apply(

In [7]:
results_df = pd.read_csv(os.path.join(BASE_DIR, "results/gru_model/random_search.csv"))
results_df.head()

,dropout_rate,hidden_dim,learning_rate,epochs,fine_tune_epochs,early_stopping_patience,listnet_temperature,listnet_max_train_groups,sequence_length,min_train_size,...,raw_mean_ic,trained_folds,skipped_folds,coverage,skipped_train_too_small,skipped_empty_test,missing_strategy,allow_short_sequences,add_listing_age_features,precompute_sequences
0,0.1,32,0.0010,10,2,3,0.5,252,10,10000,...,0.020328,94,9,0.912621,9,0,ffill_zero_indicator,True,True,True
1,0.1,64,0.0005,10,2,3,0.5,252,10,10000,...,0.018892,94,9,0.912621,9,0,ffill_zero_indicator,True,True,True
2,0.2,32,0.0002,10,2,3,0.5,252,20,10000,...,0.017646,94,9,0.912621,9,0,ffill_zero_indicator,True,True,True
3,0.1,32,0.0010,10,3,3,0.5,252,20,10000,...,0.017309,94,9,0.912621,9,0,ffill_zero_indicator,True,True,True
4,0.1,64,0.0002,10,2,3,0.5,378,10,10000,...,0.016738,94,9,0.912621,9,0,ffill_zero_indicator,True,True,True

In [ ]:
results_df["output"]

In [10]:
import json
with open(os.path.join(BASE_DIR, "results/gru_model/best_params.json"), "r") as f:
    best_params = json.load(f)

In [14]:
best_params["output_dim"]

KeyError: 'output_dim'

In [20]:
model = GRURegressionModel(
    dropout_rate=best_params['dropout_rate'], 
    hidden_dim = best_params["hidden_dim"],
    output_dim=1
)

wf = WalkForwardGRUValidator(
    feature_matrix=feature_matrix_stock,
    model=model,
    validation_start="2025-07-01",
    validation_end="2026-06-30",
    rebalance_date=1,
    min_train_size=best_params.get("min_train_size", 10000),
    sequence_length=best_params.get("sequence_length", 10),

    training_mode="listnet",
    transfer_learning=True,
    reset_model_every_n_folds=26,

    missing_strategy="ffill_zero_indicator",
    allow_short_sequences=True,
    add_listing_age_features=True,
    precompute_sequences=True,
    verbose=1,

    fit_kwargs={
        "epochs": best_params.get("epochs", 10),
        "fine_tune_epochs": best_params.get("fine_tune_epochs", 2),
        "learning_rate": best_params.get("learning_rate", 0.001),
        "verbose": 1,
        "early_stopping_patience": best_params.get("early_stopping_patience", 3),
        "early_stopping_min_delta": 1e-4,
        "restore_best_weights": True,
        "listnet_target_transform": "zscore",
        "listnet_temperature": best_params.get("listnet_temperature", 0.5),
        "listnet_max_train_groups": best_params.get("listnet_max_train_groups", 252),
    },
    predict_kwargs={"verbose": 0},
)

X_test, test_preds = wf.run_data()

daily_ic = test_preds.groupby("Date").apply(
    lambda x: x["prediction"].corr(
        x["future_return_5d"],
        method="spearman",
    ),
    include_groups = False
)

mean_ic = daily_ic.dropna().mean()

GRU fold 1/50 2025-07-01: fresh training (train=98864, test=197)
ListNet epoch 1/10: loss = 5.340822
ListNet epoch 2/10: loss = 5.307484
ListNet epoch 3/10: loss = 5.222168
ListNet epoch 4/10: loss = 5.300815
ListNet epoch 5/10: loss = 5.291175
ListNet epoch 6/10: loss = 5.287746
Early stopping at epoch 6/10
GRU fold 2/50 2025-07-08: fine-tune training (train=99849, test=197)
ListNet epoch 1/2: loss = 5.215633
ListNet epoch 2/2: loss = 5.206924
GRU fold 3/50 2025-07-15: fine-tune training (train=100834, test=197)
ListNet epoch 1/2: loss = 5.287105
ListNet epoch 2/2: loss = 5.323132
GRU fold 4/50 2025-07-22: fine-tune training (train=101819, test=197)
ListNet epoch 1/2: loss = 5.256243
ListNet epoch 2/2: loss = 5.256379
GRU fold 5/50 2025-07-29: fine-tune training (train=102804, test=197)
ListNet epoch 1/2: loss = 5.119458
ListNet epoch 2/2: loss = 5.149082
GRU fold 6/50 2025-08-05: fine-tune training (train=103789, test=197)
ListNet epoch 1/2: loss = 5.002885
ListNet epoch 2/2: loss = 4.911101
GRU fold 7/50 2025-08-12: fine-tune training (train=104774, test=197)
ListNet epoch 1/2: loss = 4.886067
ListNet epoch 2/2: loss = 5.026710
GRU fold 8/50 2025-08-19: fine-tune training (train=105759, test=197)
ListNet epoch 1/2: loss = 5.133918
ListNet epoch 2/2: loss = 5.330587
GRU fold 9/50 2025-08-26: fine-tune training (train=106744, test=197)
ListNet epoch 1/2: loss = 5.095152
ListNet epoch 2/2: loss = 5.321547
GRU fold 10/50 2025-09-02: fine-tune training (train=107729, test=197)
ListNet epoch 1/2: loss = 4.827606
ListNet epoch 2/2: loss = 4.912780
GRU fold 11/50 2025-09-09: fine-tune training (train=108714, test=197)
ListNet epoch 1/2: loss = 4.846688
ListNet epoch 2/2: loss = 4.914873
GRU fold 12/50 2025-09-16: fine-tune training (train=109699, test=197)
ListNet epoch 1/2: loss = 4.856165
ListNet epoch 2/2: loss = 4.809601
GRU fold 13/50 2025-09-23: fine-tune training (train=110684, test=198)
ListNet epoch 1/2: loss = 4.769028
ListNet epoch 2/2: loss = 4.889646
GRU fold 14/50 2025-09-30: fine-tune training (train=111673, test=198)
ListNet epoch 1/2: loss = 4.739263
ListNet epoch 2/2: loss = 5.080742
GRU fold 15/50 2025-10-07: fine-tune training (train=112663, test=200)
ListNet epoch 1/2: loss = 4.695204
ListNet epoch 2/2: loss = 4.845499
GRU fold 16/50 2025-10-14: fine-tune training (train=113658, test=200)
ListNet epoch 1/2: loss = 4.646755
ListNet epoch 2/2: loss = 4.760745
GRU fold 17/50 2025-10-21: fine-tune training (train=114658, test=200)
ListNet epoch 1/2: loss = 4.822422
ListNet epoch 2/2: loss = 4.831874
GRU fold 18/50 2025-10-28: fine-tune training (train=115658, test=200)
ListNet epoch 1/2: loss = 4.801307
ListNet epoch 2/2: loss = 4.746490
GRU fold 19/50 2025-11-04: fine-tune training (train=116658, test=200)
ListNet epoch 1/2: loss = 4.750773
ListNet epoch 2/2: loss = 4.763465
GRU fold 20/50 2025-11-11: fine-tune training (train=117658, test=200)
ListNet epoch 1/2: loss = 4.826896
ListNet epoch 2/2: loss = 5.566218
GRU fold 21/50 2025-11-18: fine-tune training (train=118658, test=200)
ListNet epoch 1/2: loss = 5.553588
ListNet epoch 2/2: loss = 5.514044
GRU fold 22/50 2025-11-25: fine-tune training (train=119658, test=200)
ListNet epoch 1/2: loss = 5.029153
ListNet epoch 2/2: loss = 4.707797
GRU fold 23/50 2025-12-02: fine-tune training (train=120658, test=200)
ListNet epoch 1/2: loss = 4.782905
ListNet epoch 2/2: loss = 4.786028
GRU fold 24/50 2025-12-09: fine-tune training (train=121658, test=200)
ListNet epoch 1/2: loss = 4.729443
ListNet epoch 2/2: loss = 4.739760
GRU fold 25/50 2025-12-16: fine-tune training (train=122658, test=200)
ListNet epoch 1/2: loss = 5.106639
ListNet epoch 2/2: loss = 4.914844
GRU fold 26/50 2025-12-23: fine-tune training (train=123658, test=200)
ListNet epoch 1/2: loss = 4.907918
ListNet epoch 2/2: loss = 4.967068
GRU fold 27/50 2025-12-30: fresh training (train=124258, test=200)
ListNet epoch 1/10: loss = 4.827960
ListNet epoch 2/10: loss = 4.878614
ListNet epoch 3/10: loss = 5.028555
ListNet epoch 4/10: loss = 5.002360
Early stopping at epoch 4/10
GRU fold 28/50 2026-01-06: fine-tune training (train=125058, test=200)
ListNet epoch 1/2: loss = 4.911489
ListNet epoch 2/2: loss = 5.020443
GRU fold 29/50 2026-01-13: fine-tune training (train=126058, test=200)
ListNet epoch 1/2: loss = 5.002052
ListNet epoch 2/2: loss = 4.912697
GRU fold 30/50 2026-01-20: fine-tune training (train=127058, test=200)
ListNet epoch 1/2: loss = 4.945731
ListNet epoch 2/2: loss = 4.846026
GRU fold 31/50 2026-01-27: fine-tune training (train=127858, test=200)
ListNet epoch 1/2: loss = 4.935331
ListNet epoch 2/2: loss = 5.106457
GRU fold 32/50 2026-02-03: fine-tune training (train=128858, test=200)
ListNet epoch 1/2: loss = 4.770621
ListNet epoch 2/2: loss = 5.069562
GRU fold 33/50 2026-02-10: fine-tune training (train=129858, test=200)
ListNet epoch 1/2: loss = 4.771193
ListNet epoch 2/2: loss = 4.741999
GRU fold 34/50 2026-02-17: fine-tune training (train=130858, test=200)
ListNet epoch 1/2: loss = 4.871366
ListNet epoch 2/2: loss = 4.990757
GRU fold 35/50 2026-02-24: fine-tune training (train=131858, test=200)
ListNet epoch 1/2: loss = 4.816534
ListNet epoch 2/2: loss = 4.808356
GRU fold 36/50 2026-03-03: fine-tune training (train=132858, test=200)
ListNet epoch 1/2: loss = 4.858301
ListNet epoch 2/2: loss = 4.774754
GRU fold 37/50 2026-03-10: fine-tune training (train=133858, test=200)
ListNet epoch 1/2: loss = 4.741100
ListNet epoch 2/2: loss = 4.768485
GRU fold 38/50 2026-03-17: fine-tune training (train=134858, test=200)
ListNet epoch 1/2: loss = 4.967047
ListNet epoch 2/2: loss = 4.939029
GRU fold 39/50 2026-03-24: fine-tune training (train=135858, test=200)
ListNet epoch 1/2: loss = 5.097283
ListNet epoch 2/2: loss = 5.066588
GRU fold 40/50 2026-03-31: fine-tune training (train=136858, test=200)
ListNet epoch 1/2: loss = 4.944987
ListNet epoch 2/2: loss = 5.033815
GRU fold 41/50 2026-04-07: fine-tune training (train=137458, test=200)
ListNet epoch 1/2: loss = 4.863241
ListNet epoch 2/2: loss = 5.079771
GRU fold 42/50 2026-04-14: fine-tune training (train=138458, test=200)
ListNet epoch 1/2: loss = 5.068607
ListNet epoch 2/2: loss = 5.075268
GRU fold 43/50 2026-04-21: fine-tune training (train=139458, test=200)
ListNet epoch 1/2: loss = 5.034271
ListNet epoch 2/2: loss = 5.090397
GRU fold 44/50 2026-04-28: fine-tune training (train=140458, test=200)
ListNet epoch 1/2: loss = 5.000800
ListNet epoch 2/2: loss = 4.877758
GRU fold 45/50 2026-05-05: fine-tune training (train=141458, test=200)
ListNet epoch 1/2: loss = 4.959224
ListNet epoch 2/2: loss = 5.041340
GRU fold 46/50 2026-05-12: fine-tune training (train=142458, test=200)
ListNet epoch 1/2: loss = 4.955367
ListNet epoch 2/2: loss = 5.178796
GRU fold 47/50 2026-05-19: fine-tune training (train=143458, test=200)
ListNet epoch 1/2: loss = 5.034670
ListNet epoch 2/2: loss = 5.063853
GRU fold 48/50 2026-05-26: fine-tune training (train=144458, test=200)
ListNet epoch 1/2: loss = 4.966752
ListNet epoch 2/2: loss = 5.069524
GRU fold 49/50 2026-06-02: fine-tune training (train=145458, test=200)
ListNet epoch 1/2: loss = 4.935800
ListNet epoch 2/2: loss = 5.258067
GRU fold 50/50 2026-06-09: skipped (train=146258, test=0, reason=empty_test)

/home/gordon1999/.local/lib/python3.10/site-packages/pandas/core/nanops.py:1632: ConstantInputWarning: An input array is constant; the correlation coefficient is not defined.
  return spearmanr(a, b)[0]

In [25]:
daily_ic.isna().sum(), len(daily_ic)

(np.int64(1), 49)

In [24]:
daily_ic = test_preds.groupby("Date").apply(
    lambda x: x["prediction"].corr(x["future_return_5d"], method="spearman"),
    include_groups=False,
)

daily_ic.mean()

/home/gordon1999/.local/lib/python3.10/site-packages/pandas/core/nanops.py:1632: ConstantInputWarning: An input array is constant; the correlation coefficient is not defined.
  return spearmanr(a, b)[0]

np.float64(0.05578925339018039)

In [23]:
mean_ic

np.float64(0.05578925339018039)

In [11]:
best_params

{'dropout_rate': 0.1,
 'hidden_dim': 32,
 'learning_rate': 0.001,
 'epochs': 10,
 'fine_tune_epochs': 2,
 'early_stopping_patience': 3,
 'listnet_temperature': 0.5,
 'listnet_max_train_groups': 252,
 'sequence_length': 10,
 'min_train_size': 10000,
 'model_type': 'gru',
 'raw_mean_ic': 0.020327647815369766,
 'trained_folds': 94,
 'skipped_folds': 9,
 'coverage': 0.912621359223301,
 'skipped_train_too_small': 9,
 'skipped_empty_test': 0,
 'missing_strategy': 'ffill_zero_indicator',
 'allow_short_sequences': True,
 'add_listing_age_features': True,
 'precompute_sequences': True}

In [6]:
import json

In [ ]:
XGBoostTuner(20, 42, feature_matrix_stock).run_data()

In [ ]:
import json
with open(os.path.join(BASE_DIR, "results/xgboost_model/best_params.json"), "r") as f:
    best_params = json.load(f)
    
int_params = [
    "max_depth",
    "n_estimators",
    "min_child_weight",
]

for p in int_params:
    best_params[p] = int(best_params[p])

In [ ]:
best_params

In [ ]:
model = XGBoostRegressionModel(params=best_params)

wf = WalkForwardValidator(
    feature_matrix=feature_matrix_stock,
    model=model,
    validation_start="2025-07-01",
    validation_end="2026-12-31",
    rebalance_date=1,
    min_train_size=25000,
)

X_test, test_preds = wf.run_data()

daily_ic = test_preds.groupby("Date").apply(
    lambda x: x["prediction"].corr(
        x["future_return_5d"],
        method="spearman",
    ),
    include_groups = False
)

mean_ic = daily_ic.dropna().mean()

In [ ]:
mean_ic

In [ ]:
LightGBMTuner(20, 42, feature_matrix_stock).run_data()

In [ ]:
results_df = pd.read_csv(os.path.join(BASE_DIR, "results/lightgbm_model/random_search.csv"))
results_df.head()

In [ ]:
import json
with open(os.path.join(BASE_DIR, "results/lightgbm_model/best_params.json"), "r") as f:
    best_params = json.load(f)

In [ ]:
int_params = [
    "num_leaves",
    "max_depth",
    "n_estimators",
    "min_child_samples",
]

for p in int_params:
    best_params[p] = int(best_params[p])

In [ ]:
model = LightGBMRegressionModel(params=best_params)

wf = WalkForwardValidator(
    feature_matrix=feature_matrix_market,
    model=model,
    validation_start="2025-07-01",
    validation_end="2026-12-31",
    rebalance_date=1,
    min_train_size=25000,
)

X_test, test_preds = wf.run_data()

daily_ic = test_preds.groupby("Date").apply(
    lambda x: x["prediction"].corr(
        x["future_return_5d"],
        method="spearman",
    )
)

mean_ic = daily_ic.dropna().mean()

In [ ]:
X_test

In [ ]:
mean_ic

In [ ]:
monthly_ic = daily_ic.groupby(daily_ic.index.to_period("M")).mean()
monthly_ic.plot(figsize=(10, 4))

In [ ]:
print("Mean IC:", daily_ic.mean())
print("Std IC :", daily_ic.std())
print("ICIR   :", daily_ic.mean() / daily_ic.std())
print("N days :", daily_ic.count())

In [ ]:
daily_ic_no_june = daily_ic[daily_ic.index < "2026-06-01"]

print("Mean IC:", daily_ic_no_june.mean())
print("Std IC :", daily_ic_no_june.std())
print("ICIR   :", daily_ic_no_june.mean() / daily_ic_no_june.std())
print("N days :", daily_ic_no_june.count())

In [ ]:
import shap
import numpy as np

explainer = shap.TreeExplainer(model.model)
shap_values = explainer.shap_values(X_test)

In [ ]:
shap.summary_plot(
    shap_values,
    X_test,
    max_display=40,
    show=False
)

In [ ]:
mean_shap = np.abs(shap_values).mean(axis=0)

importance = pd.DataFrame({
    "feature": X_test.columns,
    "mean_abs_shap": mean_shap
}).sort_values("mean_abs_shap", ascending=False)

importance.head(40)

In [ ]:
LightGBMTuner(20, 42, feature_matrix_market).run_data()

In [ ]:
shap.summary_plot(
    shap_values,
    X_test,
    max_display=40
)

In [ ]:
import matplotlib.pyplot as plt
import seaborn as sns

sns.lineplot(test_preds[test_preds["Ticker"] == "CBA.AX"], x= "Date", y="future_return_5d")
sns.lineplot(test_preds[test_preds["Ticker"] == "CBA.AX"], x= "Date", y="prediction")

In [ ]:
mean_ic

In [ ]:
test_preds

In [ ]:
test_preds

In [ ]:
test_preds

In [ ]:
test_preds

In [ ]:
test_preds.tail(20)

In [ ]:
import matplotlib.pyplot as plt
import seaborn as sns

sns.lineplot(test_preds[test_preds["Ticker"] == "CBA.AX"], x= "Date", y="future_return_5d")
sns.lineplot(test_preds[test_preds["Ticker"] == "CBA.AX"], x= "Date", y="prediction")

In [ ]:
import matplotlib.pyplot as plt
import seaborn as sns

sns.lineplot(test_preds[test_preds["Ticker"] == "ASX.AX"], x= "Date", y="future_return_5d")
sns.lineplot(test_preds[test_preds["Ticker"] == "ASX.AX"], x= "Date", y="prediction")

In [ ]:
tmp = test_preds.sort_values("Date").copy()

daily_avg = (
    tmp.groupby("Date")[["future_return_5d", "prediction"]]
       .mean()
       .reset_index()
)

daily_avg["future_return_5d_ma63"] = (
    daily_avg["future_return_5d"]
    .rolling(63, min_periods=10)
    .mean()
)

daily_avg["prediction_ma63"] = (
    daily_avg["prediction"]
    .rolling(63, min_periods=10)
    .mean()
)

daily_avg.plot(
    x="Date",
    y=["future_return_5d_ma63", "prediction_ma63"],
    figsize=(10, 4)
)

In [ ]:
ticker = "CBA.AX"   # change this

tmp = (
    test_preds[test_preds["Ticker"] == ticker]
    .sort_values("Date")
    .copy()
)

tmp[["future_return_5d", "prediction"]].describe()

In [ ]:
import matplotlib.pyplot as plt

fig, ax = plt.subplots(figsize=(10, 4))

ax.plot(tmp["Date"], tmp["future_return_5d"], label="Actual 5d return")
ax.plot(tmp["Date"], tmp["prediction"], label="Prediction")

ax.axhline(0, linestyle="--")
ax.set_title(f"{ticker}: Actual vs Predicted 5-Day Return")
ax.set_xlabel("Date")
ax.set_ylabel("Return")
ax.legend()

plt.tight_layout()
plt.show()

In [ ]:
tmp["actual_ma21"] = tmp["future_return_5d"].rolling(21, min_periods=5).mean()
tmp["pred_ma21"] = tmp["prediction"].rolling(21, min_periods=5).mean()

tmp.plot(
    x="Date",
    y=["actual_ma21", "pred_ma21"],
    figsize=(10, 4),
    title=f"{ticker}: Rolling Actual vs Prediction"
)

In [ ]:
test_preds[test_preds["Ticker"] == "CBA.AX"].tail(20)

In [ ]:
mean_ic

In [ ]:
import shap
import numpy as np

explainer = shap.TreeExplainer(model.model)
shap_values = explainer.shap_values(X_test)

In [ ]:
shap_importance = (
    pd.DataFrame({
        "feature": X_test.columns,
        "mean_abs_shap": np.abs(shap_values).mean(axis=0)
    })
    .sort_values("mean_abs_shap", ascending=False)
    .reset_index(drop=True)
)

In [ ]:
shap_importance

In [ ]:
feature_matrix_subset = feature_matrix_market[["Date", "Ticker"] + shap_importance["feature"].tolist()[:10] + ["future_return_5d"]]

In [ ]:
LightGBMTuner(20, 42, feature_matrix_subset).run_data()

In [ ]:
shap.summary_plot(
    shap_values,
    X_test,
    max_display=40
)

In [ ]:
test_preds

In [ ]:
daily_ic.describe()

In [ ]:
0.014099/0.264

In [ ]:
positive_rate = (daily_ic > 0).mean()
print(positive_rate)

In [ ]:
bad_dates = daily_ic.sort_values().head(10).index

bad_preds = test_preds[test_preds["Date"].isin(bad_dates)].copy()

bad_summary = (
    bad_preds
    .groupby("Date")
    .agg(
        n_stocks=("Ticker", "count"),
        avg_target=("future_return_5d", "mean"),
        avg_prediction=("prediction", "mean"),
        std_target=("future_return_5d", "std"),
        std_prediction=("prediction", "std"),
    )
)

bad_summary

In [ ]:
test_preds["prediction"].describe()

In [ ]:
date = test_preds["Date"].iloc[0]

tmp = test_preds[test_preds["Date"] == date]

print(tmp["prediction"].describe())
print(tmp["future_return_5d"].describe())

In [ ]:
date = test_preds["Date"].iloc[0]

tmp = test_preds[test_preds["Date"] == date].copy()

tmp[["prediction", "future_return_5d"]].corr(method="spearman")

In [ ]:
bad_date = "2026-06-02"

tmp = test_preds[test_preds["Date"] == bad_date].copy()

tmp.sort_values("prediction", ascending=False)[
    ["Ticker", "prediction", "future_return_5d"]
].head(20)

tmp.sort_values("prediction", ascending=True)[
    ["Ticker", "prediction", "future_return_5d"]
].head(20)

In [ ]:
best_params

In [ ]:
directional_accuracy = (
    (output_test["prediction"] > 0)
    ==
    (output_test["future_return_5d"] > 0)
).mean()

In [ ]:
directional_accuracy

In [ ]:
import matplotlib.pyplot as plt

plt.figure(figsize=(8, 6))
plt.scatter(
    output_test["prediction"],
    output_test["future_return_5d"],
    alpha=0.2
)
plt.xlabel("Prediction")
plt.ylabel("Future Return 5D")

In [ ]:
output_test["decile"] = pd.qcut(
    output_test["prediction"],
    10,
    labels=False,
    duplicates="drop"
)

output_test.groupby("decile")["future_return_5d"].mean()

In [ ]:
output_test["future_return_5d"].corr(output_test["prediction"])

In [ ]:
daily_ic = (
    output_test
    .groupby("Date")
    .apply(lambda x: x["prediction"].corr(x["future_return_5d"]))
)

In [ ]:
print(daily_ic.mean())
print(daily_ic.std())
print((daily_ic > 0).mean())

In [ ]:
sns.scatterplot(data=output_test, x=)